const CDR_Health_VM = require('./CDR_Health_VM.js').document;
const document  ={
    "UpTime" : 183421986,
    "CollectionType" : "CDR_Health_Daemon",
    "StartTime" : 1566492421106,
    "AvgCpuPerCpu" : [ 
        0.0, 
        0.0
    ],
    "AvgCpuTotal" : 0.0,
    "BootTimeDateTime" : "2019-07-19 04:25:49",
    "BootTimeEpoch" : 1563510349,
    "CPUCount" : 2,
    "DiskIOCountersPerDisk" : {
        "dm-0" : [ 
            11808, 
            1221398, 
            150324224, 
            5002846208, 
            19792, 
            4428108, 
            0, 
            0, 
            445558
        ],
        "dm-1" : [ 
            456, 
            0, 
            1867776, 
            0, 
            314, 
            0, 
            0, 
            0, 
            190
        ],
        "dm-2" : [ 
            8935, 
            3393404, 
            98636800, 
            13899382784, 
            8859, 
            2666987, 
            0, 
            0, 
            383733
        ],
        "dm-3" : [ 
            377, 
            337, 
            1541120, 
            1380352, 
            197, 
            1245, 
            0, 
            0, 
            610
        ],
        "dm-4" : [ 
            519, 
            126832, 
            2122752, 
            519503872, 
            551, 
            342769, 
            0, 
            0, 
            42901
        ],
        "dm-5" : [ 
            822, 
            3518532, 
            41714688, 
            14411907072, 
            2449, 
            2384564, 
            0, 
            0, 
            987943
        ],
        "vda1" : [ 
            553, 
            60, 
            2161664, 
            133120, 
            129, 
            146, 
            36, 
            64, 
            249
        ],
        "vda2" : [ 
            20056, 
            4518557, 
            298083328, 
            33835020288, 
            18805, 
            3208739, 
            3145, 
            3741934, 
            1802702
        ],
        "vdb" : [ 
            323, 
            90256, 
            1381376, 
            764792832, 
            113, 
            136934, 
            13, 
            96437, 
            80474
        ],
        "vdc" : [ 
            302, 
            47, 
            1278976, 
            253952, 
            68, 
            107, 
            11, 
            15, 
            175
        ]
    },
    "LoadAverage" : [ 
        0.0, 
        0.0, 
        0.0
    ],
    "MachineIP" : "10.25.16.53",
    "MachineName" : "zrdm6yrsrv01dmn",
    "NICIOCounters" : {
        "eth0" : [ 
            2372370192, 
            3394304834, 
            18298620, 
            26947916, 
            0, 
            0, 
            0, 
            0
        ],
        "eth1" : [ 
            40028098, 
            480737746, 
            602480, 
            7586736, 
            0, 
            0, 
            0, 
            0
        ],
        "lo" : [ 
            2102038, 
            2102038, 
            6946, 
            6946, 
            0, 
            0, 
            0, 
            0
        ]
    },
    "NICNumberOfINetConnections" : 35,
    "PartitionsDiskInodeUsagePercent" : [ 
        {
            "inodes_percent" : 10.0639483065954,
            "mount_point" : "/"
        }, 
        {
            "inodes_percent" : 0.099609375,
            "mount_point" : "/boot"
        }, 
        {
            "inodes_percent" : 0.02109375,
            "mount_point" : "/home"
        }, 
        {
            "inodes_percent" : 0.125885009765625,
            "mount_point" : "/tmp"
        }, 
        {
            "inodes_percent" : 2.1365625,
            "mount_point" : "/var"
        }, 
        {
            "inodes_percent" : 0.134895833333333,
            "mount_point" : "/var/log"
        }, 
        {
            "inodes_percent" : 0.01922607421875,
            "mount_point" : "/log"
        }, 
        {
            "inodes_percent" : 0.00335693359375,
            "mount_point" : "/conf"
        }
    ],
    "PartitionsDiskUsagePercent" : {
        "/" : 26.6,
        "/boot" : 39.4,
        "/conf" : 0.2,
        "/home" : 0.2,
        "/log" : 0.7,
        "/tmp" : 1.2,
        "/var" : 30.7,
        "/var/log" : 5.3
    },
    "RAMAvailable" : 1755598848,
    "RAMCacheUsageBytes" : 1175867392,
    "RAMUsageBytes" : 2397868032,
    "SwapUsageBytes" : 1287647232,
    "Top10CPUUsagePerProcess" : [ 
        {
            "cpu_percent" : 0.0,
            "name" : "init",
            "pid" : 1
        }, 
        {
            "cpu_percent" : 0.0,
            "name" : "kthreadd",
            "pid" : 2
        }, 
        {
            "cpu_percent" : 0.0,
            "name" : "migration/0",
            "pid" : 3
        }, 
        {
            "cpu_percent" : 0.0,
            "name" : "ksoftirqd/0",
            "pid" : 4
        }, 
        {
            "cpu_percent" : 0.0,
            "name" : "stopper/0",
            "pid" : 5
        }, 
        {
            "cpu_percent" : 0.0,
            "name" : "watchdog/0",
            "pid" : 6
        }, 
        {
            "cpu_percent" : 0.0,
            "name" : "migration/1",
            "pid" : 7
        }, 
        {
            "cpu_percent" : 0.0,
            "name" : "stopper/1",
            "pid" : 8
        }, 
        {
            "cpu_percent" : 0.0,
            "name" : "ksoftirqd/1",
            "pid" : 9
        }, 
        {
            "cpu_percent" : 0.0,
            "name" : "watchdog/1",
            "pid" : 10
        }
    ],
    "Top10ProcessOpenFilesDesc" : [ 
        {
            "name" : "java",
            "open_files" : 72,
            "pid" : 11686
        }, 
        {
            "name" : "rsyslogd",
            "open_files" : 5,
            "pid" : 1470
        }, 
        {
            "name" : "health_vm.py",
            "open_files" : 3,
            "pid" : 21650
        }, 
        {
            "name" : "corosync",
            "open_files" : 2,
            "pid" : 1568
        }, 
        {
            "name" : "hald",
            "open_files" : 2,
            "pid" : 1616
        }, 
        {
            "name" : "filebeat",
            "open_files" : 2,
            "pid" : 10226
        }, 
        {
            "name" : "udevd",
            "open_files" : 1,
            "pid" : 471
        }, 
        {
            "name" : "dhclient",
            "open_files" : 1,
            "pid" : 1257
        }, 
        {
            "name" : "dhclient",
            "open_files" : 1,
            "pid" : 1362
        }, 
        {
            "name" : "rpcbind",
            "open_files" : 1,
            "pid" : 1503
        }
    ],
    "Top10ProcessOpenNetConnectionsDesc" : [ 
        {
            "connections" : 14,
            "name" : "java",
            "pid" : 11686
        }, 
        {
            "connections" : 4,
            "name" : "ntpd",
            "pid" : 1805
        }, 
        {
            "connections" : 3,
            "name" : "rpcbind",
            "pid" : 1503
        }, 
        {
            "connections" : 3,
            "name" : "rpc.statd",
            "pid" : 1527
        }, 
        {
            "connections" : 3,
            "name" : "corosync",
            "pid" : 1568
        }, 
        {
            "connections" : 1,
            "name" : "dhclient",
            "pid" : 1257
        }, 
        {
            "connections" : 1,
            "name" : "dhclient",
            "pid" : 1362
        }, 
        {
            "connections" : 1,
            "name" : "sshd",
            "pid" : 1792
        }, 
        {
            "connections" : 1,
            "name" : "filebeat",
            "pid" : 10226
        }
    ],
    "Top10RAMUsagePerProcess" : [ 
        {
            "memory_percent" : 9.78028263463606,
            "name" : "java",
            "pid" : 11686
        }, 
        {
            "memory_percent" : 0.724929242724574,
            "name" : "filebeat",
            "pid" : 10226
        }, 
        {
            "memory_percent" : 0.365866887567429,
            "name" : "cib",
            "pid" : 1889
        }, 
        {
            "memory_percent" : 0.350877192982456,
            "name" : "health_vm.py",
            "pid" : 21650
        }, 
        {
            "memory_percent" : 0.319714406871592,
            "name" : "crmd",
            "pid" : 1894
        }, 
        {
            "memory_percent" : 0.309556916462038,
            "name" : "pengine",
            "pid" : 1893
        }, 
        {
            "memory_percent" : 0.257881916708579,
            "name" : "health_stats.py",
            "pid" : 21791
        }, 
        {
            "memory_percent" : 0.246146563711133,
            "name" : "corosync",
            "pid" : 1568
        }, 
        {
            "memory_percent" : 0.152165123319823,
            "name" : "stonithd",
            "pid" : 1890
        }, 
        {
            "memory_percent" : 0.14812185043835,
            "name" : "rsyslogd",
            "pid" : 1470
        }
    ],
    "TopCpuProcess" : 45.8,
    "TopProcessOpenFilesDesc" : {
        "name" : "java",
        "open_files" : 72,
        "pid" : 11686
    },
    "TopProcessOpenNetConnectionsDesc" : "java",
    "TotalNICDrops" : 0,
    "TotalNICErrors" : 0,
    "TotalRAMBytes" : 4153466880,
    "TotalRAMUsagePercent" : 16.0,
    "TotalSwapUsagePercent" : 0.0,
    "UnsuccessfulMaintenanceAttempts" : {
        "TOTAL" : 0.0,
        "AGG_DIAMETER_5_MIN" : 0.0,
        "AGG_IUCS_KPI_OVER_TIME_DAY" : 0.0,
        "AGG_KPI_OVER_CELL_WEEK" : 0.0,
        "AGG_GI_FIXED_LINE_5_MIN" : 0.0,
        "AGG_IPTV" : 0.0,
        "AGG_IUCS_KPI_OVER_TIME_5_MIN" : 0.0,
        "CDR_GI_SAMPLE" : 0.0,
        "AGG_LTE_HOUR" : 0.0,
        "AGG_IU_COUNTERS_HOUR" : 0.0,
        "AGG_ROAME_ISUP_5_M_MED" : 0.0,
        "AGG_SMPP_5_MIN" : 0.0,
        "AGG_VOICE_CALL_QR" : 0.0,
        "AGG_DATA_APN_WEEK" : 0.0,
        "AGG_VOICE_LEG_PERF_5_MIN" : 0.0,
        "AGG_GI_WEEK" : 0.0,
        "AGG_GB_COUNTERS_HOUR" : 0.0,
        "AGG_QVIP_VOIP_5_MIN_MINIMUM" : 0.0,
        "AGG_CGI_HOUR" : 0.0,
        "AGG_VOICE_CALL_QR_WEEK" : 0.0,
        "AGG_QCONNECT_VOICE_5_MIN" : 0.0,
        "AGG_SLA_PER_USER_5_MIN" : 0.0,
        "AGG_MIDEACOM_MOS" : 0.0,
        "CDR_TCAP" : 0.0,
        "AGG_C_ISUP_HOUR" : 0.0,
        "CDR_S1AP_TRANS" : 0.0,
        "CDR_IU_RAB" : 0.0,
        "CDR_IU_STATISTICS" : 0.0,
        "AGG_QROAM_DATA_WEEK" : 0.0,
        "AGG_GI_FIXED_LINE_DAY" : 0.0,
        "AGG_M2M_HOUR" : 0.0,
        "AGG_VOICE_R70_WEEK" : 0.0,
        "AGG_ROAME_ISUP_1_D_MIN" : 0.0,
        "CDR_S1AP" : 0.0,
        "AGG_SIGTRAN_STATS_15_MIN" : 0.0,
        "AGG_DID_CON_UNDIRECT_5_MIN" : 0.0,
        "CDR_WIRELINE_CALL_VIEW" : 0.0,
        "AGG_DATA_GGSN_5_MIN" : 0.0,
        "AGG_IUCS_KPI_OVER_CELL_MONTH" : 0.0,
        "AGG_GN_SESSION_5_MIN" : 0.0,
        "AGG_CON_CALL_DIRECT_WEEK" : 0.0,
        "AGG_CGI_SLM_5_MIN" : 0.0,
        "AGG_BM_TERMINALS_PS_WEEK" : 0.0,
        "AGG_KPI_OVER_NE_HOUR" : 0.0,
        "AGG_IUPS_KPI_OVER_PAIR_WEEK" : 0.0,
        "AGG_GB_DAY" : 0.0,
        "AGG_QCELL_RELEASE_CAUSE_MONTH" : 0.0,
        "AGG_GSM_A_SCCP_HOUR" : 0.0,
        "AGG_CN_BICC_WEEK" : 0.0,
        "AGG_CONTROL_PLANE_ATTR_5_MIN" : 0.0,
        "AGG_IUPS_KPI_OVER_CELL_HOUR" : 0.0,
        "AGG_IU_SCCP_COUNTERS_TAC_HR" : 0.0,
        "AGG_VOICE_LEG_PERF_DAY" : 0.0,
        "CDR_HPA_T38" : 0.0,
        "AGG_H248_MAINTENANCE_5_MIN" : 0.0,
        "AGG_QICARE_5_MIN" : 0.0,
        "AGG_CN_ISUP_QUALITY_5M" : 0.0,
        "CDR_USERPLANE_CAPTURE_WL" : 0.0,
        "AGG_GI_DAY" : 0.0,
        "AGG_QVIP_ACTIVITY_15_MIN" : 0.0,
        "AGG_TOP_WEB_PER_WEEK" : 0.0,
        "AGG_2ND_A10_A11" : 0.0,
        "AGG_CON_CALL_UNDIRECT_WEEK" : 0.0,
        "AGG_DATA_GGSN_HOUR" : 0.0,
        "AGG_CN_BICC" : 0.0,
        "AGG_CONTROL_PLANE_ATTR_HOUR" : 0.0,
        "AGG_ROAME_CN_1_H_FULL" : 0.0,
        "AGG_QVIP_GN_MONTH" : 0.0,
        "AGG_2ND_GI" : 0.0,
        "AGG_CONTROL_PLANE_5_MIN" : 0.0,
        "CDR_FRAUD_MANAGEMENT_CALL_VIEW" : 0.0,
        "CDR_CN_BICC" : 0.0,
        "CDR_HPA_MGCP" : 0.0,
        "AGG_WIRE_Q_CALLING_P_HOUR" : 0.0,
        "AGG_QVIP_CN_MONTH" : 0.0,
        "AGG_SIP_REG_5_M" : 0.0,
        "CDR_ROAMING_OPERATOR_5_MIN" : 0.0,
        "AGG_QCELL_HOUR" : 0.0,
        "AGG_KPI_OVER_TIME_WEEK" : 0.0,
        "AGG_QICARE_VOLTE_CALLS_15_MIN" : 0.0,
        "AGG_GB_SESSION_5_MIN" : 0.0,
        "AGG_DIRECTED_CC_W" : 0.0,
        "AGG_QVIP_DATA_DAY" : 0.0,
        "AGG_SERVICE_PROFILE_15_M" : 0.0,
        "CDR_MASTER_REG_COMPOSITE" : 0.0,
        "AGG_GN_SESSION" : 0.0,
        "AGG_CONTROL_PLANE_ATTR_DAY" : 0.0,
        "AGG_GN_HOUR" : 0.0,
        "AGG_ACCESS_MOBILITY_DATA_5_MIN" : 0.0,
        "AGG_BM_TERMINALS_CS_HOUR" : 0.0,
        "CDR_P56X" : 0.0,
        "AGG_ROAM_DATA_5_M_MIN" : 0.0,
        "AGG_CGI_15_MIN" : 0.0,
        "AGG_ROAME_ISUP_5_M_MIN" : 0.0,
        "AGG_KPN_VOIP_HOUR" : 0.0,
        "AGG_IUPS_KPI_OVER_PAIR_MONTH" : 0.0,
        "AGG_IUCS_KPI_OVER_PAIR_WEEK" : 0.0,
        "AGG_DIRECTED_CC_H" : 0.0,
        "AGG_CN_Q931_DAY" : 0.0,
        "AGG_QICARE_GI_15_MIN" : 0.0,
        "AGG_WIRE_Q_CALLING_P_DAY" : 0.0,
        "AGG_CGI_5_MIN" : 0.0,
        "AGG_DIRECTED_CC_D" : 0.0,
        "AGG_ROAM_DATA_D_FULL" : 0.0,
        "CDR_GSM_A_SCCP" : 0.0,
        "AGG_KPI_OVER_NE_MONTH" : 0.0,
        "AGG_IUPS_KPI_OVER_CELL_5_MIN" : 0.0,
        "AGG_QVIP_VOICE_5_MIN" : 0.0,
        "AGG_KPI_OVER_CELL_5_MIN" : 0.0,
        "AGG_QICARE_CP_15_MIN" : 0.0,
        "AGG_DIAMETER_NE_NAME_5_MIN" : 0.0,
        "AGG_QCONNECT_15_MINUTES" : 0.0,
        "CDR_MASTER_MOBILITY" : 0.0,
        "AGG_QVIP_GI_MONTH" : 0.0,
        "AGG_DATA_SGSN_DAY" : 0.0,
        "AGG_TAC_VOICE_HOUR" : 0.0,
        "AGG_SIP_REG_HOUR" : 0.0,
        "AGG_ACCESS_MOBILITY_CS_HOUR" : 0.0,
        "AGG_GI_5_MIN" : 0.0,
        "AGG_SIP_MONTH" : 0.0,
        "AGG_NET_STAT_SS7_15_MIN" : 0.0,
        "AGG_HPA_5_MIN" : 0.0,
        "AGG_TAC_VOICE_5_MIN" : 0.0,
        "AGG_QCONNECT_MINPREF_MONTH" : 0.0,
        "AGG_DID_CON_UNDIRECT_WEEK" : 0.0,
        "AGG_2ND_IU" : 0.0,
        "AGG_DIAMETER_NE_NAME_DAY" : 0.0,
        "AGG_KPN_SS7_HOUR" : 0.0,
        "AGG_ROAME_CN_15_M_MED" : 0.0,
        "AGG_ROAM_DATA_5_M_FULL" : 0.0,
        "AGG_CGI_DAY" : 0.0,
        "AGG_TAC_DATA_HOUR" : 0.0,
        "AGG_KPI_OVER_CELL_DAY" : 0.0,
        "AGG_VOICE_CALL_QR_DAY" : 0.0,
        "CALL_QR" : 0.0,
        "AGG_SIP_DAY" : 0.0,
        "AGG_QVIP_MASTER_MONTH_PROF" : 0.0,
        "CDR_LCSAP" : 0.0,
        "AGG_QCONNECT_MINPREF_DAY" : 0.0,
        "CDR_VIDEO" : 0.0,
        "AGG_REG_PERFORMANCE_HOUR" : 0.0,
        "AGG_GN_NE_NAME_HOUR" : 0.0,
        "AGG_ROAME_ISUP_15_M_FULL" : 0.0,
        "CDR_SIP_REG" : 0.0,
        "AGG_ROAM_DATA_H_MIN" : 0.0,
        "CDR_PESQ" : 0.0,
        "AGG_QICARE_VOLTE_REG_15_MIN" : 0.0,
        "AGG_IU_DAY" : 0.0,
        "AGG_HS_5_MIN" : 0.0,
        "AGG_CAP_IN_SESS_15_M" : 0.0,
        "AGG_QCONNECT_MINPREF_HOUR" : 0.0,
        "AGG_CELL_5_MIN" : 0.0,
        "AGG_CN_Q931_HOUR" : 0.0,
        "AGG_A10_A11" : 0.0,
        "AGG_IU_SCCP_COUNTERS_HOUR" : 0.0,
        "AGG_GN_SESSION_HOUR" : 0.0,
        "AGG_VOICE_PERFORMANCE_5_MIN" : 0.0,
        "AGG_MASTER_CLASSIFY_D" : 0.0,
        "CDR_GN_SAMPLE" : 0.0,
        "AGG_BM_TERMINALS_PS_MONTH" : 0.0,
        "AGG_QCONNECT_HOUR" : 0.0,
        "AGG_TAC_VOICE_DAY" : 0.0,
        "AGG_BM_TERMINALS_PS_5_MIN" : 0.0,
        "CDR_MASTER_DATA_SAMPLE" : 0.0,
        "AGG_GB_COUNTERS_5_MIN" : 0.0,
        "AGG_KPI_OVER_NE_DAY" : 0.0,
        "AGG_MASTER_CLASSIFY_H" : 0.0,
        "AGG_QCELL_RELEASE_CAUSE_HOUR" : 0.0,
        "AGG_IU_SCCP_COUNTERS_L_SAC_D" : 0.0,
        "AGG_DNS_DAY" : 0.0,
        "AGG_IU_SCCP_COUNTERS_L_SAC_H" : 0.0,
        "AGG_GLOBE_ROAMING_LOG_5_MIN" : 0.0,
        "AGG_QICARE_ANALYZE_15_MIN" : 0.0,
        "AGG_IUCS_KPI_OVER_CELL_DAY" : 0.0,
        "AGG_IUPS_KPI_OVER_APN_WEEK" : 0.0,
        "AGG_QVIP_DATA_5_MIN" : 0.0,
        "AGG_QVIP_DATA_MONTH" : 0.0,
        "CDR_GN_SESSION_SAMPLE" : 0.0,
        "AGG_CONTROL_PLANE_WEEK" : 0.0,
        "AGG_ROAMING_ANALYZE_DAY" : 0.0,
        "AGG_ROAME_CN_1_D_MED" : 0.0,
        "AGG_GB_5_MIN" : 0.0,
        "AGG_IUCS_KPI_OVER_NE_DAY" : 0.0,
        "AGG_ROAMING_VOICE_ANALYZE_DAY" : 0.0,
        "AGG_SIP_HOUR" : 0.0,
        "AGG_TAC_DATA_MONTH" : 0.0,
        "AGG_VOICE_LEG_PERF_WEEK" : 0.0,
        "AGG_DIAMETER_DAY" : 0.0,
        "AGG_QVIP_CN_5_MIN_EXTEND" : 0.0,
        "AGG_QVIP_GSM_HOUR" : 0.0,
        "CDR_CN_MEGACO" : 0.0,
        "AGG_ROAME_CN_15_M_MIN" : 0.0,
        "AGG_SMS_HOUR" : 0.0,
        "AGG_QVIP_MASTER_HOUR_PROF" : 0.0,
        "CDR_IU_SCCP_SAMPLE" : 0.0,
        "CDR_CN_ISUP_QUALITY" : 0.0,
        "AGG_ROAME_CN_5_M_MED" : 0.0,
        "AGG_HOST_NAME_WEEK" : 0.0,
        "AGG_CN_WEEK" : 0.0,
        "AGG_IUPS_KPI_OVER_APN_DAY" : 0.0,
        "AGG_QVIP_VOIP_HOUR" : 0.0,
        "AGG_IUPS_KPI_OVER_PAIR_5_MIN" : 0.0,
        "AGG_DATA_APN_5_MIN" : 0.0,
        "CDR_HPA_UDPTL" : 0.0,
        "AGG_ACCESS_MOBILITY_CS_5_MIN" : 0.0,
        "AGG_SLA_PER_USER_DAY" : 0.0,
        "AGG_KPN_GEN_HOUR" : 0.0,
        "CDR_CN" : 0.0,
        "AGG_GN_DAY" : 0.0,
        "CDR_IU_SAMPLE" : 0.0,
        "AGG_QVIP_ISUP_MONTH" : 0.0,
        "AGG_ROAME_ISUP_5_M_FULL" : 0.0,
        "AGG_IU_COUNTERS_5_MIN" : 0.0,
        "AGG_ACCESS_MOBILITY_DATA_MONTH" : 0.0,
        "AGG_ROAME_ISUP_1_H_MED" : 0.0,
        "AGG_BM_TERMINALS_CS_DAY" : 0.0,
        "AGG_GI_NE_NAME_5_MIN" : 0.0,
        "AGG_MASTER_CLASSIFY_5_M" : 0.0,
        "AGG_SIGTRAN_STATS_HOUR" : 0.0,
        "AGG_CONTROL_PLANE_DAY" : 0.0,
        "AGG_ROAME_ISUP_1_D_FULL" : 0.0,
        "AGG_QCELL_DAY" : 0.0,
        "CDR_LDAP" : 0.0,
        "AGG_GI_NE_NAME_HOUR" : 0.0,
        "AGG_IUCS_KPI_OVER_TIME_HOUR" : 0.0,
        "AGG_QVIP_CN_DAY" : 0.0,
        "AGG_CANTV_D" : 0.0,
        "AGG_CANTV_H" : 0.0,
        "CDR_ISUP_MAINTENANCE" : 0.0,
        "AGG_VOICE_R70" : 0.0,
        "AGG_CON_CALL_UNDIRECT_MONTH" : 0.0,
        "AGG_KPI_OVER_NE_5_MIN" : 0.0,
        "CDR_SERVICE_PROFILE" : 0.0,
        "AGG_QVIP_MASTER_DAY_PROF" : 0.0,
        "AGG_QICARE_GN_15_MIN" : 0.0,
        "AGG_QCONNECT_VOICE_DAY" : 0.0,
        "AGG_CGI_MONTH" : 0.0,
        "AGG_GI_FIXED_LINE_HOUR" : 0.0,
        "AGG_IUCS_KPI_OVER_CELL_WEEK" : 0.0,
        "AGG_CON_CALL_UNDIRECT_5_MIN" : 0.0,
        "AGG_KPI_OVER_NE_PAIR_WEEK" : 0.0,
        "CDR_HPA_H323" : 0.0,
        "AGG_TAC_DAY" : 0.0,
        "AGG_CN_BICC_5_MIN" : 0.0,
        "AGG_TOP_WEB_PER_DAY" : 0.0,
        "AGG_GI_IMSI" : 0.0,
        "AGG_CAP_IN_SESS_WEEK" : 0.0,
        "AGG_NET_STAT_SS7_5_MIN" : 0.0,
        "AGG_MTP_STATISTICS_5_MIN" : 0.0,
        "AGG_SLA_PER_USER_WEEK" : 0.0,
        "CDR_SIGTRAN_STATISTICS" : 0.0,
        "AGG_QVIP_VOICE_HOUR" : 0.0,
        "AGG_VOICE_PERFORMANCE_WEEK" : 0.0,
        "AGG_ROAME_CN_1_D_FULL" : 0.0,
        "AGG_CN_MEGACO" : 0.0,
        "AGG_GSM_A_SCCP_5_MIN" : 0.0,
        "AGG_DATA_GGSN_DAY" : 0.0,
        "AGG_DIAMETER_NE_NAME_MONTH" : 0.0,
        "AGG_IUPS_KPI_OVER_TIME_HOUR" : 0.0,
        "CDR_XCAP" : 0.0,
        "AGG_ROAME_CN_1_D_MIN" : 0.0,
        "AGG_DATA_SGSN_HOUR" : 0.0,
        "AGG_IU_HOUR" : 0.0,
        "CDR_MCPTT_FLOOR_CONTROL" : 0.0,
        "AGG_SIP_REG_15_M" : 0.0,
        "AGG_QVIP_VOIP_5_MIN" : 0.0,
        "AGG_SMPP_HOUR" : 0.0,
        "AGG_WIRELINE_PREF_OPC" : 0.0,
        "AGG_VOICE_R70_5_MIN" : 0.0,
        "AGG_QICARE_RC_15_MIN" : 0.0,
        "CDR_HPA_RTP" : 0.0,
        "AGG_QCELL_RELEASE_CAUSE_DAY" : 0.0,
        "AGG_CON_CALL_DIRECT_HOUR" : 0.0,
        "AGG_DID_CON_UNDIRECT_DAY" : 0.0,
        "AGG_QVIP_ISUP_5_MIN" : 0.0,
        "CDR_HPA_DIAMETER_SAMPLE" : 0.0,
        "AGG_IU_SCCP_COUNTERS_SAC_HR" : 0.0,
        "AGG_ACCESS_MOBILITY_CS_MONTH" : 0.0,
        "CDR_HPA_VOICE" : 0.0,
        "OMNIQ_HEALTH" : 0.0,
        "AGG_SIP_TRNK_CALL_VIEW_5_M" : 0.0,
        "AGG_IU_5_MIN" : 0.0,
        "CDR_SIP_STATISTICS" : 0.0,
        "AGG_QVIP_DATA_WEEK" : 0.0,
        "CDR_MASTER_SMS" : 0.0,
        "AGG_QCONNECT_VOICE_WEEK" : 0.0,
        "AGG_HOST_NAME_DAY" : 0.0,
        "AGG_QVIP_VOIP_DAY_MINIMUM" : 0.0,
        "AGG_ROAME_CN_5_M_FULL" : 0.0,
        "AGG_SIP_TRNK_CALL_VIEW_15_M" : 0.0,
        "AGG_VOICE_LEG_PERF_MONTH" : 0.0,
        "CDR_GI" : 0.0,
        "CDR_GN" : 0.0,
        "AGG_QICARE_DNS_15_MIN" : 0.0,
        "CDR_GB" : 0.0,
        "AGG_QVIP_CN_5_MIN" : 0.0,
        "CDR_GA" : 0.0,
        "AGG_TAC_DATA_DAY" : 0.0,
        "AGG_IUCS_KPI_OVER_NE_HOUR" : 0.0,
        "AGG_QVIP_GI_DAY" : 0.0,
        "AGG_QVIP_GSM_5_MIN" : 0.0,
        "CDR_SIP_TRUNKIN_CALL_VIEW" : 0.0,
        "AGG_ACCESS_MOBILITY_DATA_DAY" : 0.0,
        "AGG_GSM_A_SCCP_DAY" : 0.0,
        "AGG_DIAMETER_NE_NAME_HOUR" : 0.0,
        "AGG_ACCESS_MOBILITY_DATA_WEEK" : 0.0,
        "CDR_SYSTEM_HEALTH_RESOURCES" : 0.0,
        "AGG_GB_SESSION_HOUR" : 0.0,
        "AGG_GI_HOUR" : 0.0,
        "AGG_KPI_OVER_CELL_HOUR" : 0.0,
        "AGG_CGI_SLM_HOUR" : 0.0,
        "CDR_GTP_PRIME" : 0.0,
        "AGG_QVIP_CN_HOUR" : 0.0,
        "AGG_ROAMING_ANALYZE_HOUR" : 0.0,
        "AGG_GB" : 0.0,
        "AGG_A10_A11_DAY" : 0.0,
        "AGG_QVIP_VOIP_DAY" : 0.0,
        "AGG_WIRELINE_CALL_VIEW_1_W" : 0.0,
        "AGG_UN_DIRECTED_CC_H" : 0.0,
        "CDR_HPA_DIAMETER" : 0.0,
        "AGG_UN_DIRECTED_CC_D" : 0.0,
        "CDR_CAP_INAP_SESSION" : 0.0,
        "AGG_CONTROL_PLANE_ATTR_WEEK" : 0.0,
        "THRESHOLDS_VIOLATIONS" : 0.0,
        "AGG_CGI_SLM_DAY" : 0.0,
        "AGG_C_ISUP_WEEK" : 0.0,
        "AGG_CON_CALL_UNDIRECT_HOUR" : 0.0,
        "AGG_DATA_GGSN_WEEK" : 0.0,
        "CDR_IU" : 0.0,
        "AGG_CGI_WEEK" : 0.0,
        "AGG_VOICE_R70_HOUR" : 0.0,
        "CDR_IU_SCCP" : 0.0,
        "AGG_CANTV_CN_FILTER" : 0.0,
        "AGG_SLA_PER_USER_MONTH" : 0.0,
        "AGG_QCONNECT_VOICE_MONTH" : 0.0,
        "CDR_SYSTEM_HEALTH_CDR" : 0.0,
        "CDR_PFCP" : 0.0,
        "AGG_CN_ISUP_5_MIN" : 0.0,
        "THRESHOLDS_ACTIVE_VIOLATIONS" : 0.0,
        "AGG_QVIP_ISUP_HOUR" : 0.0,
        "AGG_DID_CON_UNDIRECT_MONTH" : 0.0,
        "AGG_VOICE_CALL_QR_HOUR" : 0.0,
        "AGG_SMS_5_MIN" : 0.0,
        "AGG_IUPS_KPI_OVER_CELL_WEEK" : 0.0,
        "AGG_DATA_SGSN_5_MIN" : 0.0,
        "AGG_CN_BICC_HOUR" : 0.0,
        "AGG_QVIP_ISUP_5_MIN_EXTEND" : 0.0,
        "AGG_QICARE_VOLTE_ACCESS_15_MIN" : 0.0,
        "AGG_DNS_5_MIN" : 0.0,
        "AGG_KPI_OVER_TIME_DAY" : 0.0,
        "CDR_WIRELINE" : 0.0,
        "AGG_BM_TERMINALS_PS_HOUR" : 0.0,
        "AGG_QCELL_5_MIN" : 0.0,
        "AGG_IU_SCCP_COUNTERS_TAC_D" : 0.0,
        "AGG_CON_CALL_DIRECT_DAY" : 0.0,
        "AGG_CN_Q931_15_MIN" : 0.0,
        "AGG_IUPS_KPI_OVER_PAIR_HOUR" : 0.0,
        "CDR_HPA_RTCP" : 0.0,
        "AGG_WIRELINE_CALL_VIEW_1_H" : 0.0,
        "AGG_SESSION_COMPOSITE_5_M" : 0.0,
        "AGG_QICARE_HOUR" : 0.0,
        "AGG_WIRELINE_CALL_VIEW_1_D" : 0.0,
        "AGG_IUCS_KPI_OVER_PAIR_DAY" : 0.0,
        "AGG_DATA_APN_HOUR" : 0.0,
        "AGG_UN_DIRECTED_CC_W" : 0.0,
        "AGG_CN_MEGACO_5_MIN" : 0.0,
        "AGG_KPI_OVER_NE_PAIR_5_MIN" : 0.0,
        "AGG_QVIP_VOICE_DAY" : 0.0,
        "AGG_IU_SCCP_COUNTERS_L_SAC" : 0.0,
        "AGG_SESSION_COMPOSITE_15_M" : 0.0,
        "AGG_BM_TERMINALS_CS_MONTH" : 0.0,
        "AGG_IUPS_KPI_OVER_PAIR_DAY" : 0.0,
        "AGG_CON_CALL_UNDIRECT_DAY" : 0.0,
        "AGG_QVIP_GSM_MONTH" : 0.0,
        "AGG_ROAME_CN_PRE_5_M_MIN" : 0.0,
        "AGG_CN_MEGACO_HOUR" : 0.0,
        "AGG_CN" : 0.0,
        "AGG_CONTROL_PLANE_MONTH" : 0.0,
        "AGG_QVIP_MASTER_5_MIN_PROF" : 0.0,
        "AGG_GI_MONTH" : 0.0,
        "AGG_SMP_HOUR" : 0.0,
        "AGG_SIP_REG_WEEK" : 0.0,
        "CDR_HPA_MEGACO" : 0.0,
        "AGG_VOICE_PERFORMANCE_DAY" : 0.0,
        "AGG_IUPS_KPI_OVER_CELL_DAY" : 0.0,
        "AGG_QROAM_DATA_MONTH" : 0.0,
        "AGG_QROAM_ACTIVE_HOUR" : 0.0,
        "CDR_GN_SESSION" : 0.0,
        "AGG_KPI_OVER_CELL_MONTH" : 0.0,
        "AGG_QCELL_WEEK" : 0.0,
        "AGG_QVIP_VOICE_MONTH" : 0.0,
        "AGG_KPI_OVER_TIME_HOUR" : 0.0,
        "AGG_ACCESS_MOBILITY_CS_WEEK" : 0.0,
        "AGG_IU_SCCP_COUNTERS_SAC" : 0.0,
        "AGG_IU_SCCP" : 0.0,
        "AGG_QVIP_ISUP_DAY" : 0.0,
        "AGG_GN_NE_NAME_5_MIN" : 0.0,
        "AGG_IU_SCCP_COUNTERS_DAY" : 0.0,
        "AGG_CAP_IN_SESS_DAY" : 0.0,
        "AGG_DID_CON_UNDIRECT_HOUR" : 0.0,
        "AGG_QVIP_VOIP_HOUR_MINIMUM" : 0.0,
        "AGG_VOICE_CALL_QR_5_MIN" : 0.0,
        "AGG_REG_PERFORMANCE_WEEK" : 0.0,
        "AGG_BM_TERMINALS_CS_WEEK" : 0.0,
        "AGG_GI_NE_NAME_DAY" : 0.0,
        "CDR_VIOLA" : 0.0,
        "AGG_IUPS_KPI_OVER_CELL_MONTH" : 0.0,
        "AGG_QROAM_LOCATION_HOUR" : 0.0,
        "AGG_DNS_HOUR" : 0.0,
        "DASHBOARD_CALCULATION" : 0.0,
        "CDR_DAEMON_SYSTEM_HEALTH" : 0.0,
        "AGG_GB_HOUR" : 0.0,
        "AGG_KPI_OVER_NE_WEEK" : 0.0,
        "AGG_IUCS_KPI_OVER_NE_MONTH" : 0.0,
        "AGG_ROAME_ISUP_1_H_FULL" : 0.0,
        "AGG_GN_TAC_HOUR" : 0.0,
        "AGG_GN_WEEK" : 0.0,
        "AGG_CN_ISUP_QUALITY_15M" : 0.0,
        "DASHBOARD_ALARMS" : 0.0,
        "AGG_TOP_WEB_PER_5_MIN" : 0.0,
        "AGG_QCONNECT_MONTH" : 0.0,
        "AGG_ROAM_DATA_D_MIN" : 0.0,
        "AGG_IU_SCCP_COUNTERS_TAC" : 0.0,
        "AGG_REG_PERFORMANCE_DAY" : 0.0,
        "AGG_SMS_DAY" : 0.0,
        "AGG_DATA_APN_MONTH" : 0.0,
        "AGG_SIP_TRNK_CALL_VIEW_1_H" : 0.0,
        "AGG_SIP_TRNK_CALL_VIEW_1_D" : 0.0,
        "CDR_T38_FAX" : 0.0,
        "AGG_GI_FIXED_LINE_MONTH" : 0.0,
        "CDR_MASTER_MOBILITY_SAMPLE" : 0.0,
        "AGG_QCELL_RELEASE_CAUSE_5_MIN" : 0.0,
        "AGG_GN_NE_NAME_WEEK" : 0.0,
        "AGG_GI_NE_NAME_MONTH" : 0.0,
        "AGG_IUCS_KPI_OVER_TIME_MONTH" : 0.0,
        "AGG_ROAME_ISUP_1_H_MIN" : 0.0,
        "AGG_SERVICE_PROFILE_1_W" : 0.0,
        "CDR_CONCURRENT_CALLS" : 0.0,
        "AGG_ROAME_CN_5_M_MIN" : 0.0,
        "AGG_IUCS_KPI_OVER_PAIR_HOUR" : 0.0,
        "CDR_S1AP_SAMPLE" : 0.0,
        "AGG_GSM_A_SCCP" : 0.0,
        "AGG_QVIP_GN_5_MIN" : 0.0,
        "CDR_CN_ISUP" : 0.0,
        "AGG_C_ISUP_DAY" : 0.0,
        "CDR_VSE" : 0.0,
        "AGG_IUPS_KPI_OVER_APN_HOUR" : 0.0,
        "AGG_SERVICE_PROFILE_1_D" : 0.0,
        "AGG_SERVICE_PROFILE_1_H" : 0.0,
        "AGG_TAC_DATA_5_MIN" : 0.0,
        "AGG_QICARE_LOCATION_15_MIN" : 0.0,
        "AGG_REG_PERFORMANCE_MONTH" : 0.0,
        "AGG_WIRELINE_CALL_VIEW_15_M" : 0.0,
        "AGG_TAC_5_MIN" : 0.0,
        "AGG_VOICE_LEG_PERF_HOUR" : 0.0,
        "CDR_NETWORK_STATISTICS_SS7" : 0.0,
        "AGG_QICARE_WEB_HOUR" : 0.0,
        "AGG_IPTV_MEDIA_DETAIL" : 0.0,
        "CDR_SBCAP" : 0.0,
        "AGG_MTP_STATISTICS_DAY" : 0.0,
        "AGG_HPA_HOUR" : 0.0,
        "CDR_SYSTEM_HEALTH" : 0.0,
        "CDR_GSM_A" : 0.0,
        "AGG_CN_BICC_DAY" : 0.0,
        "AGG_SIP_TRNK_CALL_V_1_MON" : 0.0,
        "AGG_NET_STAT_SS7_1_D" : 0.0,
        "AGG_NET_STAT_SS7_1_H" : 0.0,
        "CDR_CN_Q931" : 0.0,
        "AGG_WIRELINE_CALL_VIEW_5_M" : 0.0,
        "AGG_VOICE_PERFORMANCE_MONTH" : 0.0,
        "CDR_DNS" : 0.0,
        "AGG_TAC_DATA_WEEK" : 0.0,
        "AGG_CN_Q931_5_MIN" : 0.0,
        "AGG_CONTROL_PLANE_HOUR" : 0.0,
        "AGG_WIRELINE_Q_PREFIX" : 0.0,
        "CDR_MASTER_DATA" : 0.0,
        "AGG_DIRECTED_CC_MON" : 0.0,
        "AGG_SIP_WEEK" : 0.0,
        "AGG_QVIP_GN_DAY" : 0.0,
        "CDR_SMPP" : 0.0,
        "CDR_HPA_HTML_XML" : 0.0,
        "CALLS_CORRELATION" : 0.0,
        "AGG_QCELL_RELEASE_CAUSE_WEEK" : 0.0,
        "REJECTED_DATA" : 0.0,
        "AGG_QVIP_GI_HOUR" : 0.0,
        "AGG_IU_SCCP_COUNTERS" : 0.0,
        "AGG_QVIP_GI_5_MIN" : 0.0,
        "AGG_LTE_DAY" : 0.0,
        "AGG_IUPS_KPI_OVER_TIME_5_MIN" : 0.0,
        "CDR_SYSTEM_HEALTH_PROCESS" : 0.0,
        "AGG_ROAME_CN_15_M_FULL" : 0.0,
        "CDR_MASTER_SESSION_COMPOSITE" : 0.0,
        "AGG_HOST_NAME_HOUR" : 0.0,
        "AGG_ROAME_ISUP_15_M_MIN" : 0.0,
        "CDR_IPTV_MASTER" : 0.0,
        "AGG_SIP_5_MIN" : 0.0,
        "AGG_GB_SESSION" : 0.0,
        "CDR_MTP_STATISTICS" : 0.0,
        "AGG_SMP_5_MIN" : 0.0,
        "AGG_KPI_OVER_TIME_5_MIN" : 0.0,
        "AGG_BM_TERMINALS_PS_DAY" : 0.0,
        "AGG_SMS_WEEK" : 0.0,
        "CDR_GB_SESSION" : 0.0,
        "AGG_QCONNECT_DAY" : 0.0,
        "AGG_QVIP_GSM_DAY" : 0.0,
        "AGG_ROAME_ISUP_PRE_5_M_MIN" : 0.0,
        "AGG_CAP_IN_SESS_5_M" : 0.0,
        "AGG_CON_CALL_DIRECT_5_MIN" : 0.0,
        "AGG_WIRELINE_Q_ROUTE" : 0.0,
        "AGG_SIP_REG_DAY" : 0.0,
        "CDR_HPA_SIP" : 0.0,
        "CDR_PROBE_STATUS" : 0.0,
        "AGG_GN_NE_NAME_MONTH" : 0.0,
        "AGG_SIGTRAN_STATS_5_MIN" : 0.0,
        "AGG_GI_NE_NAME_WEEK" : 0.0,
        "AGG_H248_MAINTENANCE_1_D" : 0.0,
        "AGG_CN_5_MIN" : 0.0,
        "AGG_H248_MAINTENANCE_1_H" : 0.0,
        "AGG_CN_HOUR" : 0.0,
        "AGG_ROAME_CN_1_H_MIN" : 0.0,
        "AGG_REG_PERFORMANCE_5_MIN" : 0.0,
        "AGG_IUCS_KPI_OVER_TIME_WEEK" : 0.0,
        "AGG_HOST_NAME_5_MIN" : 0.0,
        "AGG_DIAMETER_HOUR" : 0.0,
        "AGG_GN_5_MIN" : 0.0,
        "AGG_ROAM_DATA_H_FULL" : 0.0,
        "AGG_DATA_WEB_SITE_APPLICATION" : 0.0,
        "AGG_H248_MAINTENANCE_15_MIN" : 0.0,
        "AGG_SESSION_COMPOSITE_D" : 0.0,
        "AGG_DATA_APN_DAY" : 0.0,
        "AGG_CAP_IN_SESS_HOUR" : 0.0,
        "AGG_GI_FIXED_LINE_WEEK" : 0.0,
        "AGG_KPI_OVER_NE_PAIR_DAY" : 0.0,
        "AGG_CN_ISUP" : 0.0,
        "AGG_GN_SESSION_DAY" : 0.0,
        "AGG_SESSION_COMPOSITE_M" : 0.0,
        "AGG_MTP_STATISTICS_HOUR" : 0.0,
        "AGG_DATA_SESSION_HOUR" : 0.0,
        "AGG_HOST_NAME_MONTH" : 0.0,
        "AGG_SESSION_COMPOSITE_H" : 0.0,
        "AGG_CN_DAY" : 0.0,
        "AGG_SESSION_COMPOSITE_W" : 0.0,
        "AGG_TOP_WEB_PER_HOUR" : 0.0,
        "AGG_ACCESS_MOBILITY_CS_DAY" : 0.0,
        "AGG_SMPP_15_MIN" : 0.0,
        "AGG_QVIP_GSM_5_MIN_EXTEND" : 0.0,
        "AGG_GB_SESSION_DAY" : 0.0,
        "AGG_IUPS_KPI_OVER_APN_5_MIN" : 0.0,
        "AGG_IUCS_KPI_OVER_PAIR_5_MIN" : 0.0,
        "AGG_GN_NE_NAME_DAY" : 0.0,
        "AGG_ROAME_ISUP_1_D_MED" : 0.0,
        "AGG_SLA_PER_USER_HOUR" : 0.0,
        "CDR_SGS" : 0.0,
        "CDR_MSRP" : 0.0,
        "AGG_QVIP_VOICE_WEEK" : 0.0,
        "AGG_IUPS_KPI_OVER_APN_MONTH" : 0.0,
        "AGG_VOICE_R70_DAY" : 0.0,
        "AGG_QCONNECT_VOICE_HOUR" : 0.0,
        "AGG_IU_SCCP_COUNTERS_SAC_D" : 0.0,
        "CDR_H248_MAINTENANCE" : 0.0,
        "AGG_IUCS_KPI_OVER_NE_5_MIN" : 0.0,
        "AGG_SMS_MONTH" : 0.0,
        "AGG_SIGTRAN_STATS_DAY" : 0.0,
        "AGG_KPI_OVER_NE_PAIR_HOUR" : 0.0,
        "AGG_IUPS_KPI_OVER_TIME_DAY" : 0.0,
        "AGG_IUCS_KPI_OVER_PAIR_MONTH" : 0.0,
        "AGG_IU" : 0.0,
        "AGG_QCELL_MONTH" : 0.0,
        "AGG_ROAME_ISUP_15_M_MED" : 0.0,
        "AGG_GN_MONTH" : 0.0,
        "AGG_CN_MEGACO_DAY" : 0.0,
        "AGG_QVIP_DATA_HOUR" : 0.0,
        "AGG_QROAM_DATA_DAY" : 0.0,
        "AGG_CONTROL_PLANE_ATTR_MONTH" : 0.0,
        "AGG_KPI_OVER_TIME_MONTH" : 0.0,
        "AGG_CANTV" : 0.0,
        "AGG_IUPS_KPI_OVER_TIME_MONTH" : 0.0,
        "AGG_IUCS_KPI_OVER_CELL_5_MIN" : 0.0,
        "AGG_IUPS_KPI_OVER_TIME_WEEK" : 0.0,
        "AGG_DATA_SGSN_WEEK" : 0.0,
        "AGG_SIP_REG" : 0.0,
        "AGG_QROAM_DATA_HOUR" : 0.0,
        "AGG_QROAM_DATA_PRE_5_M_MIN" : 0.0,
        "AGG_CON_CALL_DIRECT_MONTH" : 0.0,
        "AGG_UN_DIRECTED_CC_MON" : 0.0,
        "AGG_QVIP_LOCATION_15_MIN" : 0.0,
        "AGG_QROAM_DATA_5_MIN" : 0.0,
        "AGG_KPI_OVER_NE_PAIR_MONTH" : 0.0,
        "AGG_ROAMING_VOICE_ANALYZE_HOUR" : 0.0,
        "AGG_2ND_IU_SCCP" : 0.0,
        "AGG_QVIP_GN_HOUR" : 0.0,
        "AGG_VOICE_PERFORMANCE_HOUR" : 0.0,
        "AGG_LTE_5_MIN" : 0.0,
        "AGG_ROAME_CN_1_H_MED" : 0.0,
        "AGG_BM_TERMINALS_CS_5_MIN" : 0.0,
        "AGG_HPA_DAY" : 0.0,
        "AGG_ACCESS_MOBILITY_DATA_HOUR" : 0.0,
        "AGG_IUCS_KPI_OVER_NE_WEEK" : 0.0,
        "AGG_DIAMETER_NE_NAME_WEEK" : 0.0,
        "CDR_MTP_EVENT" : 0.0,
        "CDR_A10_A11" : 0.0,
        "AGG_GN" : 0.0,
        "CDR_USERPLANE_CAPTURE" : 0.0,
        "AGG_GI" : 0.0,
        "AGG_IUCS_KPI_OVER_CELL_HOUR" : 0.0,
        "CDR_PFCP_SESSION" : 0.0,
        "AGG_QVIP_ANALYZE_HOUR" : 0.0,
        "AGG_TAC_HOUR" : 0.0,
        "AGG_SERVICE_PROFILE_5_M" : 0.0
    },
    "OpenDBConnections" : 11.0,
    "UnsuccessfulAggregationAttempts" : {
        "TOTAL" : 0.0,
        "AGG_CONTROL_PLANE_DAY" : 0.0,
        "AGG_GI_NE_NAME_DAY" : 0.0,
        "AGG_QROAM_DATA_DAY" : 0.0,
        "AGG_SIP_HOUR" : 0.0,
        "AGG_QROAM_DATA_HOUR" : 0.0,
        "AGG_CONTROL_PLANE_HOUR" : 0.0,
        "AGG_GI_NE_NAME_HOUR" : 0.0,
        "AGG_SIP_DAY" : 0.0
    },
    "TotalMaintenanceAttempts" : {
        "TOTAL" : 36.0,
        "AGG_DIAMETER_5_MIN" : 0.0,
        "AGG_IUCS_KPI_OVER_TIME_DAY" : 0.0,
        "AGG_KPI_OVER_CELL_WEEK" : 0.0,
        "AGG_GI_FIXED_LINE_5_MIN" : 0.0,
        "AGG_IPTV" : 0.0,
        "AGG_IUCS_KPI_OVER_TIME_5_MIN" : 0.0,
        "CDR_GI_SAMPLE" : 0.0,
        "AGG_LTE_HOUR" : 0.0,
        "AGG_IU_COUNTERS_HOUR" : 0.0,
        "AGG_ROAME_ISUP_5_M_MED" : 0.0,
        "AGG_SMPP_5_MIN" : 0.0,
        "AGG_VOICE_CALL_QR" : 0.0,
        "AGG_DATA_APN_WEEK" : 0.0,
        "AGG_VOICE_LEG_PERF_5_MIN" : 0.0,
        "AGG_GI_WEEK" : 0.0,
        "AGG_GB_COUNTERS_HOUR" : 0.0,
        "AGG_QVIP_VOIP_5_MIN_MINIMUM" : 0.0,
        "AGG_CGI_HOUR" : 0.0,
        "AGG_VOICE_CALL_QR_WEEK" : 0.0,
        "AGG_QCONNECT_VOICE_5_MIN" : 0.0,
        "AGG_SLA_PER_USER_5_MIN" : 0.0,
        "AGG_MIDEACOM_MOS" : 0.0,
        "CDR_TCAP" : 0.0,
        "AGG_C_ISUP_HOUR" : 0.0,
        "CDR_S1AP_TRANS" : 0.0,
        "CDR_IU_RAB" : 0.0,
        "CDR_IU_STATISTICS" : 0.0,
        "AGG_QROAM_DATA_WEEK" : 0.0,
        "AGG_GI_FIXED_LINE_DAY" : 0.0,
        "AGG_M2M_HOUR" : 0.0,
        "AGG_VOICE_R70_WEEK" : 0.0,
        "AGG_ROAME_ISUP_1_D_MIN" : 0.0,
        "CDR_S1AP" : 0.0,
        "AGG_SIGTRAN_STATS_15_MIN" : 0.0,
        "AGG_DID_CON_UNDIRECT_5_MIN" : 0.0,
        "CDR_WIRELINE_CALL_VIEW" : 0.0,
        "AGG_DATA_GGSN_5_MIN" : 0.0,
        "AGG_IUCS_KPI_OVER_CELL_MONTH" : 0.0,
        "AGG_GN_SESSION_5_MIN" : 0.0,
        "AGG_CON_CALL_DIRECT_WEEK" : 0.0,
        "AGG_CGI_SLM_5_MIN" : 0.0,
        "AGG_BM_TERMINALS_PS_WEEK" : 0.0,
        "AGG_KPI_OVER_NE_HOUR" : 0.0,
        "AGG_IUPS_KPI_OVER_PAIR_WEEK" : 0.0,
        "AGG_GB_DAY" : 0.0,
        "AGG_QCELL_RELEASE_CAUSE_MONTH" : 0.0,
        "AGG_GSM_A_SCCP_HOUR" : 0.0,
        "AGG_CN_BICC_WEEK" : 0.0,
        "AGG_CONTROL_PLANE_ATTR_5_MIN" : 0.0,
        "AGG_IUPS_KPI_OVER_CELL_HOUR" : 0.0,
        "AGG_IU_SCCP_COUNTERS_TAC_HR" : 0.0,
        "AGG_VOICE_LEG_PERF_DAY" : 0.0,
        "CDR_HPA_T38" : 0.0,
        "AGG_H248_MAINTENANCE_5_MIN" : 0.0,
        "AGG_QICARE_5_MIN" : 0.0,
        "AGG_CN_ISUP_QUALITY_5M" : 0.0,
        "CDR_USERPLANE_CAPTURE_WL" : 1.0,
        "AGG_GI_DAY" : 0.0,
        "AGG_QVIP_ACTIVITY_15_MIN" : 0.0,
        "AGG_TOP_WEB_PER_WEEK" : 0.0,
        "AGG_2ND_A10_A11" : 0.0,
        "AGG_CON_CALL_UNDIRECT_WEEK" : 0.0,
        "AGG_DATA_GGSN_HOUR" : 0.0,
        "AGG_CN_BICC" : 0.0,
        "AGG_CONTROL_PLANE_ATTR_HOUR" : 0.0,
        "AGG_ROAME_CN_1_H_FULL" : 0.0,
        "AGG_QVIP_GN_MONTH" : 0.0,
        "AGG_2ND_GI" : 0.0,
        "AGG_CONTROL_PLANE_5_MIN" : 0.0,
        "CDR_FRAUD_MANAGEMENT_CALL_VIEW" : 0.0,
        "CDR_CN_BICC" : 0.0,
        "CDR_HPA_MGCP" : 0.0,
        "AGG_WIRE_Q_CALLING_P_HOUR" : 0.0,
        "AGG_QVIP_CN_MONTH" : 0.0,
        "AGG_SIP_REG_5_M" : 0.0,
        "CDR_ROAMING_OPERATOR_5_MIN" : 0.0,
        "AGG_QCELL_HOUR" : 0.0,
        "AGG_KPI_OVER_TIME_WEEK" : 0.0,
        "AGG_QICARE_VOLTE_CALLS_15_MIN" : 0.0,
        "AGG_GB_SESSION_5_MIN" : 0.0,
        "AGG_DIRECTED_CC_W" : 0.0,
        "AGG_QVIP_DATA_DAY" : 0.0,
        "AGG_SERVICE_PROFILE_15_M" : 0.0,
        "CDR_MASTER_REG_COMPOSITE" : 1.0,
        "AGG_GN_SESSION" : 0.0,
        "AGG_CONTROL_PLANE_ATTR_DAY" : 0.0,
        "AGG_GN_HOUR" : 0.0,
        "AGG_ACCESS_MOBILITY_DATA_5_MIN" : 0.0,
        "AGG_BM_TERMINALS_CS_HOUR" : 0.0,
        "CDR_P56X" : 0.0,
        "AGG_ROAM_DATA_5_M_MIN" : 0.0,
        "AGG_CGI_15_MIN" : 0.0,
        "AGG_ROAME_ISUP_5_M_MIN" : 0.0,
        "AGG_KPN_VOIP_HOUR" : 0.0,
        "AGG_IUPS_KPI_OVER_PAIR_MONTH" : 0.0,
        "AGG_IUCS_KPI_OVER_PAIR_WEEK" : 0.0,
        "AGG_DIRECTED_CC_H" : 0.0,
        "AGG_CN_Q931_DAY" : 0.0,
        "AGG_QICARE_GI_15_MIN" : 0.0,
        "AGG_WIRE_Q_CALLING_P_DAY" : 0.0,
        "AGG_CGI_5_MIN" : 0.0,
        "AGG_DIRECTED_CC_D" : 0.0,
        "AGG_ROAM_DATA_D_FULL" : 0.0,
        "CDR_GSM_A_SCCP" : 0.0,
        "AGG_KPI_OVER_NE_MONTH" : 0.0,
        "AGG_IUPS_KPI_OVER_CELL_5_MIN" : 0.0,
        "AGG_QVIP_VOICE_5_MIN" : 0.0,
        "AGG_KPI_OVER_CELL_5_MIN" : 0.0,
        "AGG_QICARE_CP_15_MIN" : 0.0,
        "AGG_DIAMETER_NE_NAME_5_MIN" : 0.0,
        "AGG_QCONNECT_15_MINUTES" : 0.0,
        "CDR_MASTER_MOBILITY" : 0.0,
        "AGG_QVIP_GI_MONTH" : 0.0,
        "AGG_DATA_SGSN_DAY" : 0.0,
        "AGG_TAC_VOICE_HOUR" : 0.0,
        "AGG_SIP_REG_HOUR" : 0.0,
        "AGG_ACCESS_MOBILITY_CS_HOUR" : 0.0,
        "AGG_GI_5_MIN" : 0.0,
        "AGG_SIP_MONTH" : 0.0,
        "AGG_NET_STAT_SS7_15_MIN" : 0.0,
        "AGG_HPA_5_MIN" : 0.0,
        "AGG_TAC_VOICE_5_MIN" : 0.0,
        "AGG_QCONNECT_MINPREF_MONTH" : 0.0,
        "AGG_DID_CON_UNDIRECT_WEEK" : 0.0,
        "AGG_2ND_IU" : 0.0,
        "AGG_DIAMETER_NE_NAME_DAY" : 0.0,
        "AGG_KPN_SS7_HOUR" : 0.0,
        "AGG_ROAME_CN_15_M_MED" : 0.0,
        "AGG_ROAM_DATA_5_M_FULL" : 0.0,
        "AGG_CGI_DAY" : 0.0,
        "AGG_TAC_DATA_HOUR" : 0.0,
        "AGG_KPI_OVER_CELL_DAY" : 0.0,
        "AGG_VOICE_CALL_QR_DAY" : 0.0,
        "CALL_QR" : 0.0,
        "AGG_SIP_DAY" : 0.0,
        "AGG_QVIP_MASTER_MONTH_PROF" : 0.0,
        "CDR_LCSAP" : 0.0,
        "AGG_QCONNECT_MINPREF_DAY" : 0.0,
        "CDR_VIDEO" : 0.0,
        "AGG_REG_PERFORMANCE_HOUR" : 0.0,
        "AGG_GN_NE_NAME_HOUR" : 0.0,
        "AGG_ROAME_ISUP_15_M_FULL" : 0.0,
        "CDR_SIP_REG" : 1.0,
        "AGG_ROAM_DATA_H_MIN" : 0.0,
        "CDR_PESQ" : 0.0,
        "AGG_QICARE_VOLTE_REG_15_MIN" : 0.0,
        "AGG_IU_DAY" : 0.0,
        "AGG_HS_5_MIN" : 0.0,
        "AGG_CAP_IN_SESS_15_M" : 0.0,
        "AGG_QCONNECT_MINPREF_HOUR" : 0.0,
        "AGG_CELL_5_MIN" : 0.0,
        "AGG_CN_Q931_HOUR" : 0.0,
        "AGG_A10_A11" : 0.0,
        "AGG_IU_SCCP_COUNTERS_HOUR" : 0.0,
        "AGG_GN_SESSION_HOUR" : 0.0,
        "AGG_VOICE_PERFORMANCE_5_MIN" : 0.0,
        "AGG_MASTER_CLASSIFY_D" : 0.0,
        "CDR_GN_SAMPLE" : 0.0,
        "AGG_BM_TERMINALS_PS_MONTH" : 0.0,
        "AGG_QCONNECT_HOUR" : 0.0,
        "AGG_TAC_VOICE_DAY" : 0.0,
        "AGG_BM_TERMINALS_PS_5_MIN" : 0.0,
        "CDR_MASTER_DATA_SAMPLE" : 0.0,
        "AGG_GB_COUNTERS_5_MIN" : 0.0,
        "AGG_KPI_OVER_NE_DAY" : 0.0,
        "AGG_MASTER_CLASSIFY_H" : 0.0,
        "AGG_QCELL_RELEASE_CAUSE_HOUR" : 0.0,
        "AGG_IU_SCCP_COUNTERS_L_SAC_D" : 0.0,
        "AGG_DNS_DAY" : 0.0,
        "AGG_IU_SCCP_COUNTERS_L_SAC_H" : 0.0,
        "AGG_GLOBE_ROAMING_LOG_5_MIN" : 0.0,
        "AGG_QICARE_ANALYZE_15_MIN" : 0.0,
        "AGG_IUCS_KPI_OVER_CELL_DAY" : 0.0,
        "AGG_IUPS_KPI_OVER_APN_WEEK" : 0.0,
        "AGG_QVIP_DATA_5_MIN" : 0.0,
        "AGG_QVIP_DATA_MONTH" : 0.0,
        "CDR_GN_SESSION_SAMPLE" : 0.0,
        "AGG_CONTROL_PLANE_WEEK" : 0.0,
        "AGG_ROAMING_ANALYZE_DAY" : 0.0,
        "AGG_ROAME_CN_1_D_MED" : 0.0,
        "AGG_GB_5_MIN" : 0.0,
        "AGG_IUCS_KPI_OVER_NE_DAY" : 0.0,
        "AGG_ROAMING_VOICE_ANALYZE_DAY" : 0.0,
        "AGG_SIP_HOUR" : 1.0,
        "AGG_TAC_DATA_MONTH" : 0.0,
        "AGG_VOICE_LEG_PERF_WEEK" : 0.0,
        "AGG_DIAMETER_DAY" : 0.0,
        "AGG_QVIP_CN_5_MIN_EXTEND" : 0.0,
        "AGG_QVIP_GSM_HOUR" : 0.0,
        "CDR_CN_MEGACO" : 0.0,
        "AGG_ROAME_CN_15_M_MIN" : 0.0,
        "AGG_SMS_HOUR" : 0.0,
        "AGG_QVIP_MASTER_HOUR_PROF" : 0.0,
        "CDR_IU_SCCP_SAMPLE" : 0.0,
        "CDR_CN_ISUP_QUALITY" : 0.0,
        "AGG_ROAME_CN_5_M_MED" : 0.0,
        "AGG_HOST_NAME_WEEK" : 0.0,
        "AGG_CN_WEEK" : 0.0,
        "AGG_IUPS_KPI_OVER_APN_DAY" : 0.0,
        "AGG_QVIP_VOIP_HOUR" : 0.0,
        "AGG_IUPS_KPI_OVER_PAIR_5_MIN" : 0.0,
        "AGG_DATA_APN_5_MIN" : 0.0,
        "CDR_HPA_UDPTL" : 0.0,
        "AGG_ACCESS_MOBILITY_CS_5_MIN" : 0.0,
        "AGG_SLA_PER_USER_DAY" : 0.0,
        "AGG_KPN_GEN_HOUR" : 0.0,
        "CDR_CN" : 0.0,
        "AGG_GN_DAY" : 0.0,
        "CDR_IU_SAMPLE" : 0.0,
        "AGG_QVIP_ISUP_MONTH" : 0.0,
        "AGG_ROAME_ISUP_5_M_FULL" : 0.0,
        "AGG_IU_COUNTERS_5_MIN" : 0.0,
        "AGG_ACCESS_MOBILITY_DATA_MONTH" : 0.0,
        "AGG_ROAME_ISUP_1_H_MED" : 0.0,
        "AGG_BM_TERMINALS_CS_DAY" : 0.0,
        "AGG_GI_NE_NAME_5_MIN" : 0.0,
        "AGG_MASTER_CLASSIFY_5_M" : 0.0,
        "AGG_SIGTRAN_STATS_HOUR" : 0.0,
        "AGG_CONTROL_PLANE_DAY" : 0.0,
        "AGG_ROAME_ISUP_1_D_FULL" : 0.0,
        "AGG_QCELL_DAY" : 0.0,
        "CDR_LDAP" : 5.0,
        "AGG_GI_NE_NAME_HOUR" : 0.0,
        "AGG_IUCS_KPI_OVER_TIME_HOUR" : 0.0,
        "AGG_QVIP_CN_DAY" : 0.0,
        "AGG_CANTV_D" : 0.0,
        "AGG_CANTV_H" : 0.0,
        "CDR_ISUP_MAINTENANCE" : 0.0,
        "AGG_VOICE_R70" : 0.0,
        "AGG_CON_CALL_UNDIRECT_MONTH" : 0.0,
        "AGG_KPI_OVER_NE_5_MIN" : 0.0,
        "CDR_SERVICE_PROFILE" : 0.0,
        "AGG_QVIP_MASTER_DAY_PROF" : 0.0,
        "AGG_QICARE_GN_15_MIN" : 0.0,
        "AGG_QCONNECT_VOICE_DAY" : 0.0,
        "AGG_CGI_MONTH" : 0.0,
        "AGG_GI_FIXED_LINE_HOUR" : 0.0,
        "AGG_IUCS_KPI_OVER_CELL_WEEK" : 0.0,
        "AGG_CON_CALL_UNDIRECT_5_MIN" : 0.0,
        "AGG_KPI_OVER_NE_PAIR_WEEK" : 0.0,
        "CDR_HPA_H323" : 0.0,
        "AGG_TAC_DAY" : 0.0,
        "AGG_CN_BICC_5_MIN" : 0.0,
        "AGG_TOP_WEB_PER_DAY" : 0.0,
        "AGG_GI_IMSI" : 0.0,
        "AGG_CAP_IN_SESS_WEEK" : 0.0,
        "AGG_NET_STAT_SS7_5_MIN" : 0.0,
        "AGG_MTP_STATISTICS_5_MIN" : 0.0,
        "AGG_SLA_PER_USER_WEEK" : 0.0,
        "CDR_SIGTRAN_STATISTICS" : 0.0,
        "AGG_QVIP_VOICE_HOUR" : 0.0,
        "AGG_VOICE_PERFORMANCE_WEEK" : 0.0,
        "AGG_ROAME_CN_1_D_FULL" : 0.0,
        "AGG_CN_MEGACO" : 0.0,
        "AGG_GSM_A_SCCP_5_MIN" : 0.0,
        "AGG_DATA_GGSN_DAY" : 0.0,
        "AGG_DIAMETER_NE_NAME_MONTH" : 0.0,
        "AGG_IUPS_KPI_OVER_TIME_HOUR" : 0.0,
        "CDR_XCAP" : 0.0,
        "AGG_ROAME_CN_1_D_MIN" : 0.0,
        "AGG_DATA_SGSN_HOUR" : 0.0,
        "AGG_IU_HOUR" : 0.0,
        "CDR_MCPTT_FLOOR_CONTROL" : 0.0,
        "AGG_SIP_REG_15_M" : 0.0,
        "AGG_QVIP_VOIP_5_MIN" : 0.0,
        "AGG_SMPP_HOUR" : 0.0,
        "AGG_WIRELINE_PREF_OPC" : 0.0,
        "AGG_VOICE_R70_5_MIN" : 0.0,
        "AGG_QICARE_RC_15_MIN" : 0.0,
        "CDR_HPA_RTP" : 0.0,
        "AGG_QCELL_RELEASE_CAUSE_DAY" : 0.0,
        "AGG_CON_CALL_DIRECT_HOUR" : 0.0,
        "AGG_DID_CON_UNDIRECT_DAY" : 0.0,
        "AGG_QVIP_ISUP_5_MIN" : 0.0,
        "CDR_HPA_DIAMETER_SAMPLE" : 0.0,
        "AGG_IU_SCCP_COUNTERS_SAC_HR" : 0.0,
        "AGG_ACCESS_MOBILITY_CS_MONTH" : 0.0,
        "CDR_HPA_VOICE" : 0.0,
        "OMNIQ_HEALTH" : 0.0,
        "AGG_SIP_TRNK_CALL_VIEW_5_M" : 0.0,
        "AGG_IU_5_MIN" : 0.0,
        "CDR_SIP_STATISTICS" : 0.0,
        "AGG_QVIP_DATA_WEEK" : 0.0,
        "CDR_MASTER_SMS" : 0.0,
        "AGG_QCONNECT_VOICE_WEEK" : 0.0,
        "AGG_HOST_NAME_DAY" : 0.0,
        "AGG_QVIP_VOIP_DAY_MINIMUM" : 0.0,
        "AGG_ROAME_CN_5_M_FULL" : 0.0,
        "AGG_SIP_TRNK_CALL_VIEW_15_M" : 0.0,
        "AGG_VOICE_LEG_PERF_MONTH" : 0.0,
        "CDR_GI" : 1.0,
        "CDR_GN" : 0.0,
        "AGG_QICARE_DNS_15_MIN" : 0.0,
        "CDR_GB" : 0.0,
        "AGG_QVIP_CN_5_MIN" : 0.0,
        "CDR_GA" : 0.0,
        "AGG_TAC_DATA_DAY" : 0.0,
        "AGG_IUCS_KPI_OVER_NE_HOUR" : 0.0,
        "AGG_QVIP_GI_DAY" : 0.0,
        "AGG_QVIP_GSM_5_MIN" : 0.0,
        "CDR_SIP_TRUNKIN_CALL_VIEW" : 0.0,
        "AGG_ACCESS_MOBILITY_DATA_DAY" : 0.0,
        "AGG_GSM_A_SCCP_DAY" : 0.0,
        "AGG_DIAMETER_NE_NAME_HOUR" : 0.0,
        "AGG_ACCESS_MOBILITY_DATA_WEEK" : 0.0,
        "CDR_SYSTEM_HEALTH_RESOURCES" : 0.0,
        "AGG_GB_SESSION_HOUR" : 0.0,
        "AGG_GI_HOUR" : 0.0,
        "AGG_KPI_OVER_CELL_HOUR" : 0.0,
        "AGG_CGI_SLM_HOUR" : 0.0,
        "CDR_GTP_PRIME" : 0.0,
        "AGG_QVIP_CN_HOUR" : 0.0,
        "AGG_ROAMING_ANALYZE_HOUR" : 0.0,
        "AGG_GB" : 0.0,
        "AGG_A10_A11_DAY" : 0.0,
        "AGG_QVIP_VOIP_DAY" : 0.0,
        "AGG_WIRELINE_CALL_VIEW_1_W" : 0.0,
        "AGG_UN_DIRECTED_CC_H" : 0.0,
        "CDR_HPA_DIAMETER" : 6.0,
        "AGG_UN_DIRECTED_CC_D" : 0.0,
        "CDR_CAP_INAP_SESSION" : 0.0,
        "AGG_CONTROL_PLANE_ATTR_WEEK" : 0.0,
        "THRESHOLDS_VIOLATIONS" : 0.0,
        "AGG_CGI_SLM_DAY" : 0.0,
        "AGG_C_ISUP_WEEK" : 0.0,
        "AGG_CON_CALL_UNDIRECT_HOUR" : 0.0,
        "AGG_DATA_GGSN_WEEK" : 0.0,
        "CDR_IU" : 0.0,
        "AGG_CGI_WEEK" : 0.0,
        "AGG_VOICE_R70_HOUR" : 0.0,
        "CDR_IU_SCCP" : 0.0,
        "AGG_CANTV_CN_FILTER" : 0.0,
        "AGG_SLA_PER_USER_MONTH" : 0.0,
        "AGG_QCONNECT_VOICE_MONTH" : 0.0,
        "CDR_SYSTEM_HEALTH_CDR" : 0.0,
        "CDR_PFCP" : 9.0,
        "AGG_CN_ISUP_5_MIN" : 0.0,
        "THRESHOLDS_ACTIVE_VIOLATIONS" : 0.0,
        "AGG_QVIP_ISUP_HOUR" : 0.0,
        "AGG_DID_CON_UNDIRECT_MONTH" : 0.0,
        "AGG_VOICE_CALL_QR_HOUR" : 0.0,
        "AGG_SMS_5_MIN" : 0.0,
        "AGG_IUPS_KPI_OVER_CELL_WEEK" : 0.0,
        "AGG_DATA_SGSN_5_MIN" : 0.0,
        "AGG_CN_BICC_HOUR" : 0.0,
        "AGG_QVIP_ISUP_5_MIN_EXTEND" : 0.0,
        "AGG_QICARE_VOLTE_ACCESS_15_MIN" : 0.0,
        "AGG_DNS_5_MIN" : 0.0,
        "AGG_KPI_OVER_TIME_DAY" : 0.0,
        "CDR_WIRELINE" : 0.0,
        "AGG_BM_TERMINALS_PS_HOUR" : 0.0,
        "AGG_QCELL_5_MIN" : 0.0,
        "AGG_IU_SCCP_COUNTERS_TAC_D" : 0.0,
        "AGG_CON_CALL_DIRECT_DAY" : 0.0,
        "AGG_CN_Q931_15_MIN" : 0.0,
        "AGG_IUPS_KPI_OVER_PAIR_HOUR" : 0.0,
        "CDR_HPA_RTCP" : 0.0,
        "AGG_WIRELINE_CALL_VIEW_1_H" : 0.0,
        "AGG_SESSION_COMPOSITE_5_M" : 0.0,
        "AGG_QICARE_HOUR" : 0.0,
        "AGG_WIRELINE_CALL_VIEW_1_D" : 0.0,
        "AGG_IUCS_KPI_OVER_PAIR_DAY" : 0.0,
        "AGG_DATA_APN_HOUR" : 0.0,
        "AGG_UN_DIRECTED_CC_W" : 0.0,
        "AGG_CN_MEGACO_5_MIN" : 0.0,
        "AGG_KPI_OVER_NE_PAIR_5_MIN" : 0.0,
        "AGG_QVIP_VOICE_DAY" : 0.0,
        "AGG_IU_SCCP_COUNTERS_L_SAC" : 0.0,
        "AGG_SESSION_COMPOSITE_15_M" : 0.0,
        "AGG_BM_TERMINALS_CS_MONTH" : 0.0,
        "AGG_IUPS_KPI_OVER_PAIR_DAY" : 0.0,
        "AGG_CON_CALL_UNDIRECT_DAY" : 0.0,
        "AGG_QVIP_GSM_MONTH" : 0.0,
        "AGG_ROAME_CN_PRE_5_M_MIN" : 0.0,
        "AGG_CN_MEGACO_HOUR" : 0.0,
        "AGG_CN" : 0.0,
        "AGG_CONTROL_PLANE_MONTH" : 0.0,
        "AGG_QVIP_MASTER_5_MIN_PROF" : 0.0,
        "AGG_GI_MONTH" : 0.0,
        "AGG_SMP_HOUR" : 0.0,
        "AGG_SIP_REG_WEEK" : 0.0,
        "CDR_HPA_MEGACO" : 0.0,
        "AGG_VOICE_PERFORMANCE_DAY" : 0.0,
        "AGG_IUPS_KPI_OVER_CELL_DAY" : 0.0,
        "AGG_QROAM_DATA_MONTH" : 0.0,
        "AGG_QROAM_ACTIVE_HOUR" : 0.0,
        "CDR_GN_SESSION" : 0.0,
        "AGG_KPI_OVER_CELL_MONTH" : 0.0,
        "AGG_QCELL_WEEK" : 0.0,
        "AGG_QVIP_VOICE_MONTH" : 0.0,
        "AGG_KPI_OVER_TIME_HOUR" : 0.0,
        "AGG_ACCESS_MOBILITY_CS_WEEK" : 0.0,
        "AGG_IU_SCCP_COUNTERS_SAC" : 0.0,
        "AGG_IU_SCCP" : 0.0,
        "AGG_QVIP_ISUP_DAY" : 0.0,
        "AGG_GN_NE_NAME_5_MIN" : 0.0,
        "AGG_IU_SCCP_COUNTERS_DAY" : 0.0,
        "AGG_CAP_IN_SESS_DAY" : 0.0,
        "AGG_DID_CON_UNDIRECT_HOUR" : 0.0,
        "AGG_QVIP_VOIP_HOUR_MINIMUM" : 0.0,
        "AGG_VOICE_CALL_QR_5_MIN" : 0.0,
        "AGG_REG_PERFORMANCE_WEEK" : 0.0,
        "AGG_BM_TERMINALS_CS_WEEK" : 0.0,
        "AGG_GI_NE_NAME_DAY" : 0.0,
        "CDR_VIOLA" : 0.0,
        "AGG_IUPS_KPI_OVER_CELL_MONTH" : 0.0,
        "AGG_QROAM_LOCATION_HOUR" : 0.0,
        "AGG_DNS_HOUR" : 0.0,
        "DASHBOARD_CALCULATION" : 0.0,
        "CDR_DAEMON_SYSTEM_HEALTH" : 0.0,
        "AGG_GB_HOUR" : 0.0,
        "AGG_KPI_OVER_NE_WEEK" : 0.0,
        "AGG_IUCS_KPI_OVER_NE_MONTH" : 0.0,
        "AGG_ROAME_ISUP_1_H_FULL" : 0.0,
        "AGG_GN_TAC_HOUR" : 0.0,
        "AGG_GN_WEEK" : 0.0,
        "AGG_CN_ISUP_QUALITY_15M" : 0.0,
        "DASHBOARD_ALARMS" : 0.0,
        "AGG_TOP_WEB_PER_5_MIN" : 0.0,
        "AGG_QCONNECT_MONTH" : 0.0,
        "AGG_ROAM_DATA_D_MIN" : 0.0,
        "AGG_IU_SCCP_COUNTERS_TAC" : 0.0,
        "AGG_REG_PERFORMANCE_DAY" : 0.0,
        "AGG_SMS_DAY" : 0.0,
        "AGG_DATA_APN_MONTH" : 0.0,
        "AGG_SIP_TRNK_CALL_VIEW_1_H" : 0.0,
        "AGG_SIP_TRNK_CALL_VIEW_1_D" : 0.0,
        "CDR_T38_FAX" : 0.0,
        "AGG_GI_FIXED_LINE_MONTH" : 0.0,
        "CDR_MASTER_MOBILITY_SAMPLE" : 0.0,
        "AGG_QCELL_RELEASE_CAUSE_5_MIN" : 0.0,
        "AGG_GN_NE_NAME_WEEK" : 0.0,
        "AGG_GI_NE_NAME_MONTH" : 0.0,
        "AGG_IUCS_KPI_OVER_TIME_MONTH" : 0.0,
        "AGG_ROAME_ISUP_1_H_MIN" : 0.0,
        "AGG_SERVICE_PROFILE_1_W" : 0.0,
        "CDR_CONCURRENT_CALLS" : 0.0,
        "AGG_ROAME_CN_5_M_MIN" : 0.0,
        "AGG_IUCS_KPI_OVER_PAIR_HOUR" : 0.0,
        "CDR_S1AP_SAMPLE" : 0.0,
        "AGG_GSM_A_SCCP" : 0.0,
        "AGG_QVIP_GN_5_MIN" : 0.0,
        "CDR_CN_ISUP" : 0.0,
        "AGG_C_ISUP_DAY" : 0.0,
        "CDR_VSE" : 0.0,
        "AGG_IUPS_KPI_OVER_APN_HOUR" : 0.0,
        "AGG_SERVICE_PROFILE_1_D" : 0.0,
        "AGG_SERVICE_PROFILE_1_H" : 0.0,
        "AGG_TAC_DATA_5_MIN" : 0.0,
        "AGG_QICARE_LOCATION_15_MIN" : 0.0,
        "AGG_REG_PERFORMANCE_MONTH" : 0.0,
        "AGG_WIRELINE_CALL_VIEW_15_M" : 0.0,
        "AGG_TAC_5_MIN" : 0.0,
        "AGG_VOICE_LEG_PERF_HOUR" : 0.0,
        "CDR_NETWORK_STATISTICS_SS7" : 0.0,
        "AGG_QICARE_WEB_HOUR" : 0.0,
        "AGG_IPTV_MEDIA_DETAIL" : 0.0,
        "CDR_SBCAP" : 0.0,
        "AGG_MTP_STATISTICS_DAY" : 0.0,
        "AGG_HPA_HOUR" : 0.0,
        "CDR_SYSTEM_HEALTH" : 0.0,
        "CDR_GSM_A" : 0.0,
        "AGG_CN_BICC_DAY" : 0.0,
        "AGG_SIP_TRNK_CALL_V_1_MON" : 0.0,
        "AGG_NET_STAT_SS7_1_D" : 0.0,
        "AGG_NET_STAT_SS7_1_H" : 0.0,
        "CDR_CN_Q931" : 0.0,
        "AGG_WIRELINE_CALL_VIEW_5_M" : 0.0,
        "AGG_VOICE_PERFORMANCE_MONTH" : 0.0,
        "CDR_DNS" : 0.0,
        "AGG_TAC_DATA_WEEK" : 0.0,
        "AGG_CN_Q931_5_MIN" : 0.0,
        "AGG_CONTROL_PLANE_HOUR" : 4.0,
        "AGG_WIRELINE_Q_PREFIX" : 0.0,
        "CDR_MASTER_DATA" : 1.0,
        "AGG_DIRECTED_CC_MON" : 0.0,
        "AGG_SIP_WEEK" : 0.0,
        "AGG_QVIP_GN_DAY" : 0.0,
        "CDR_SMPP" : 0.0,
        "CDR_HPA_HTML_XML" : 0.0,
        "CALLS_CORRELATION" : 0.0,
        "AGG_QCELL_RELEASE_CAUSE_WEEK" : 0.0,
        "REJECTED_DATA" : 0.0,
        "AGG_QVIP_GI_HOUR" : 0.0,
        "AGG_IU_SCCP_COUNTERS" : 0.0,
        "AGG_QVIP_GI_5_MIN" : 0.0,
        "AGG_LTE_DAY" : 0.0,
        "AGG_IUPS_KPI_OVER_TIME_5_MIN" : 0.0,
        "CDR_SYSTEM_HEALTH_PROCESS" : 0.0,
        "AGG_ROAME_CN_15_M_FULL" : 0.0,
        "CDR_MASTER_SESSION_COMPOSITE" : 1.0,
        "AGG_HOST_NAME_HOUR" : 0.0,
        "AGG_ROAME_ISUP_15_M_MIN" : 0.0,
        "CDR_IPTV_MASTER" : 0.0,
        "AGG_SIP_5_MIN" : 0.0,
        "AGG_GB_SESSION" : 0.0,
        "CDR_MTP_STATISTICS" : 0.0,
        "AGG_SMP_5_MIN" : 0.0,
        "AGG_KPI_OVER_TIME_5_MIN" : 0.0,
        "AGG_BM_TERMINALS_PS_DAY" : 0.0,
        "AGG_SMS_WEEK" : 0.0,
        "CDR_GB_SESSION" : 0.0,
        "AGG_QCONNECT_DAY" : 0.0,
        "AGG_QVIP_GSM_DAY" : 0.0,
        "AGG_ROAME_ISUP_PRE_5_M_MIN" : 0.0,
        "AGG_CAP_IN_SESS_5_M" : 0.0,
        "AGG_CON_CALL_DIRECT_5_MIN" : 0.0,
        "AGG_WIRELINE_Q_ROUTE" : 0.0,
        "AGG_SIP_REG_DAY" : 0.0,
        "CDR_HPA_SIP" : 1.0,
        "CDR_PROBE_STATUS" : 0.0,
        "AGG_GN_NE_NAME_MONTH" : 0.0,
        "AGG_SIGTRAN_STATS_5_MIN" : 0.0,
        "AGG_GI_NE_NAME_WEEK" : 0.0,
        "AGG_H248_MAINTENANCE_1_D" : 0.0,
        "AGG_CN_5_MIN" : 0.0,
        "AGG_H248_MAINTENANCE_1_H" : 0.0,
        "AGG_CN_HOUR" : 0.0,
        "AGG_ROAME_CN_1_H_MIN" : 0.0,
        "AGG_REG_PERFORMANCE_5_MIN" : 0.0,
        "AGG_IUCS_KPI_OVER_TIME_WEEK" : 0.0,
        "AGG_HOST_NAME_5_MIN" : 0.0,
        "AGG_DIAMETER_HOUR" : 0.0,
        "AGG_GN_5_MIN" : 0.0,
        "AGG_ROAM_DATA_H_FULL" : 0.0,
        "AGG_DATA_WEB_SITE_APPLICATION" : 0.0,
        "AGG_H248_MAINTENANCE_15_MIN" : 0.0,
        "AGG_SESSION_COMPOSITE_D" : 0.0,
        "AGG_DATA_APN_DAY" : 0.0,
        "AGG_CAP_IN_SESS_HOUR" : 0.0,
        "AGG_GI_FIXED_LINE_WEEK" : 0.0,
        "AGG_KPI_OVER_NE_PAIR_DAY" : 0.0,
        "AGG_CN_ISUP" : 0.0,
        "AGG_GN_SESSION_DAY" : 0.0,
        "AGG_SESSION_COMPOSITE_M" : 0.0,
        "AGG_MTP_STATISTICS_HOUR" : 0.0,
        "AGG_DATA_SESSION_HOUR" : 0.0,
        "AGG_HOST_NAME_MONTH" : 0.0,
        "AGG_SESSION_COMPOSITE_H" : 0.0,
        "AGG_CN_DAY" : 0.0,
        "AGG_SESSION_COMPOSITE_W" : 0.0,
        "AGG_TOP_WEB_PER_HOUR" : 0.0,
        "AGG_ACCESS_MOBILITY_CS_DAY" : 0.0,
        "AGG_SMPP_15_MIN" : 0.0,
        "AGG_QVIP_GSM_5_MIN_EXTEND" : 0.0,
        "AGG_GB_SESSION_DAY" : 0.0,
        "AGG_IUPS_KPI_OVER_APN_5_MIN" : 0.0,
        "AGG_IUCS_KPI_OVER_PAIR_5_MIN" : 0.0,
        "AGG_GN_NE_NAME_DAY" : 0.0,
        "AGG_ROAME_ISUP_1_D_MED" : 0.0,
        "AGG_SLA_PER_USER_HOUR" : 0.0,
        "CDR_SGS" : 0.0,
        "CDR_MSRP" : 0.0,
        "AGG_QVIP_VOICE_WEEK" : 0.0,
        "AGG_IUPS_KPI_OVER_APN_MONTH" : 0.0,
        "AGG_VOICE_R70_DAY" : 0.0,
        "AGG_QCONNECT_VOICE_HOUR" : 0.0,
        "AGG_IU_SCCP_COUNTERS_SAC_D" : 0.0,
        "CDR_H248_MAINTENANCE" : 0.0,
        "AGG_IUCS_KPI_OVER_NE_5_MIN" : 0.0,
        "AGG_SMS_MONTH" : 0.0,
        "AGG_SIGTRAN_STATS_DAY" : 0.0,
        "AGG_KPI_OVER_NE_PAIR_HOUR" : 0.0,
        "AGG_IUPS_KPI_OVER_TIME_DAY" : 0.0,
        "AGG_IUCS_KPI_OVER_PAIR_MONTH" : 0.0,
        "AGG_IU" : 0.0,
        "AGG_QCELL_MONTH" : 0.0,
        "AGG_ROAME_ISUP_15_M_MED" : 0.0,
        "AGG_GN_MONTH" : 0.0,
        "AGG_CN_MEGACO_DAY" : 0.0,
        "AGG_QVIP_DATA_HOUR" : 0.0,
        "AGG_QROAM_DATA_DAY" : 0.0,
        "AGG_CONTROL_PLANE_ATTR_MONTH" : 0.0,
        "AGG_KPI_OVER_TIME_MONTH" : 0.0,
        "AGG_CANTV" : 0.0,
        "AGG_IUPS_KPI_OVER_TIME_MONTH" : 0.0,
        "AGG_IUCS_KPI_OVER_CELL_5_MIN" : 0.0,
        "AGG_IUPS_KPI_OVER_TIME_WEEK" : 0.0,
        "AGG_DATA_SGSN_WEEK" : 0.0,
        "AGG_SIP_REG" : 0.0,
        "AGG_QROAM_DATA_HOUR" : 0.0,
        "AGG_QROAM_DATA_PRE_5_M_MIN" : 0.0,
        "AGG_CON_CALL_DIRECT_MONTH" : 0.0,
        "AGG_UN_DIRECTED_CC_MON" : 0.0,
        "AGG_QVIP_LOCATION_15_MIN" : 0.0,
        "AGG_QROAM_DATA_5_MIN" : 0.0,
        "AGG_KPI_OVER_NE_PAIR_MONTH" : 0.0,
        "AGG_ROAMING_VOICE_ANALYZE_HOUR" : 0.0,
        "AGG_2ND_IU_SCCP" : 0.0,
        "AGG_QVIP_GN_HOUR" : 0.0,
        "AGG_VOICE_PERFORMANCE_HOUR" : 0.0,
        "AGG_LTE_5_MIN" : 0.0,
        "AGG_ROAME_CN_1_H_MED" : 0.0,
        "AGG_BM_TERMINALS_CS_5_MIN" : 0.0,
        "AGG_HPA_DAY" : 0.0,
        "AGG_ACCESS_MOBILITY_DATA_HOUR" : 0.0,
        "AGG_IUCS_KPI_OVER_NE_WEEK" : 0.0,
        "AGG_DIAMETER_NE_NAME_WEEK" : 0.0,
        "CDR_MTP_EVENT" : 0.0,
        "CDR_A10_A11" : 0.0,
        "AGG_GN" : 0.0,
        "CDR_USERPLANE_CAPTURE" : 0.0,
        "AGG_GI" : 0.0,
        "AGG_IUCS_KPI_OVER_CELL_HOUR" : 0.0,
        "CDR_PFCP_SESSION" : 4.0,
        "AGG_QVIP_ANALYZE_HOUR" : 0.0,
        "AGG_TAC_HOUR" : 0.0,
        "AGG_SERVICE_PROFILE_5_M" : 0.0
    },
    "TotalAggregationAttempts" : {
        "TOTAL" : 8.0,
        "AGG_CONTROL_PLANE_DAY" : 1.0,
        "AGG_GI_NE_NAME_DAY" : 1.0,
        "AGG_QROAM_DATA_DAY" : 1.0,
        "AGG_SIP_HOUR" : 1.0,
        "AGG_QROAM_DATA_HOUR" : 1.0,
        "AGG_CONTROL_PLANE_HOUR" : 1.0,
        "AGG_GI_NE_NAME_HOUR" : 1.0,
        "AGG_SIP_DAY" : 1.0
    },
    "AggregationDelayRatio" : {
        "TOTAL" : 8.0,
        "AGG_CONTROL_PLANE_DAY" : 1.0,
        "AGG_GI_NE_NAME_DAY" : 1.0,
        "AGG_QROAM_DATA_DAY" : 1.0,
        "AGG_SIP_HOUR" : 1.0,
        "AGG_QROAM_DATA_HOUR" : 1.0,
        "AGG_CONTROL_PLANE_HOUR" : 1.0,
        "AGG_GI_NE_NAME_HOUR" : 1.0,
        "AGG_SIP_DAY" : 1.0
    },
    "RejectedAggregationAttempts" : 0.0,
    "TimeStamp" : 1566492422881,
    "TimeStampDisplay" : "2019-08-22T16:47:02.881Z",
    "SiteName" : "RDM6a",
    "StartTimeDisplay" : "2019-08-22T16:47:01.106Z",
    "UpTimeDisplay" : "1970-01-03T02:57:01.986Z"
}
const unique = 100
module.exports.getDocs = () => {
    const docs = [];
    const VMdocs = [];
    for(let i = 0; i < unique; i++){
        const Mdoc = new Object(document);
        const VMdoc = new Object(CDR_Health_VM);
        Mdoc.MachineIP = 'IP'+i;
        Mdoc.MachineName = Mdoc.MachineName + i;
        //Mdoc.MachineType = 'randomMiddle';
        Mdoc.StartTime = new Date();
        Mdoc.TimeStamp = new Date();
        Mdoc.StartTimeDisplay = Mdoc.StartTime.toUTCString();
        Mdoc.TimeStampDisplay = Mdoc.TimeStamp.toUTCString();
        docs.push(Mdoc);

        VMdoc.MachineIP = 'IP'+i;
        VMdoc.MachineName = Mdoc.MachineName + i;
        VMdoc.MachineType = 'randomDaemon';
        VMdoc.StartTime = new Date();
        VMdoc.TimeStamp = new Date();
        VMdoc.StartTimeDisplay = VMdoc.StartTime.toUTCString();
        VMdoc.TimeStampDisplay = VMdoc.TimeStamp.toUTCString();
        VMdocs.push(VMdoc);
    }
    return {
        "Mdocs": [...docs],
        "VMdocs": [...VMdocs]
    }
}