const CDR_Health_VM = require('./CDR_Health_VM.js').document;
module.exports.document = {
    "AverageCpuUsage" : 28,
    "BearerHashFailedToInsert" : 0,
    "BearerHashUtilization" : 0.0,
    "CDRBuffersUtilization" : 0.0,
    "CaptureDropsPps" : 0,
    "CdrTxPerType" : {
        "A11" : 0,
        "NONE_VALID" : 0,
        "diameter" : 0,
        "dns" : 2,
        "gb" : 0,
        "gi" : 0,
        "gn" : 0,
        "gtp_prime" : 0,
        "h323" : 0,
        "iu" : 0,
        "lcsap" : 0,
        "ldap" : 0,
        "mcptt" : 0,
        "megaco" : 0,
        "mgcp" : 0,
        "msrp" : 0,
        "pfcp" : 0,
        "q931" : 0,
        "radius" : 0,
        "rtcp" : 0,
        "rtp" : 0,
        "s1ap" : 0,
        "sbcap" : 0,
        "sgsap" : 0,
        "sip" : 12,
        "smpp" : 0,
        "ss7" : 0,
        "ss7ansitcap" : 0,
        "ss7tcap" : 0,
        "t38" : 0,
        "x2ap" : 0
    },
    "CipheringDataInvalid" : 0,
    "CipheringKeyNotFound" : 0,
    "CollectionType" : "CDR_Health_vProbe",
    "ConnectivityDropsPps" : 0,
    "CorrelatedGtpcFrameRate" : 0.0,
    "CorrelationHashFailedToInsert" : 0,
    "CorrelationHashUtilization" : 0.0,
    "DataCorrelationHashFailedToInsert" : 0,
    "DataCorrelationHashUtilization" : 0.0,
    "DecoderRingUtilization" : 0,
    "DecodersDropsPps" : 0,
    "DiameterResolvingRate" : 0.0,
    "DiameterResolvingRateLast10K" : 0.0,
    "DiskUsed" : 504639488,
    "FailedToSendCDRsPerSecond" : 0,
    "FailedToSendXDRsPerSecond" : 0.0,
    "FullRTPFailedToSaveBps" : 0,
    "FullRTPSavedBps" : 0,
    "FullRTPStorageUsage" : 1,
    "FullUserPlanFailedToSaveBps" : 0,
    "FullUserPlanSavedBps" : 0,
    "FullUserPlanStorageUsage" : 1,
    "GnGiCorrelationRate" : null,
    "GnGiCorrelationRateLast10K" : 0.0,
    "Immediate" : false,
    "KasmeHashFailedToInsert" : 0,
    "KasmeHashUtilization" : 0.0,
    "LBRingUtilization" : 0,
    "LastProcessUpTime" : 1564684380667,
    "LdapCurrentOpenedSession" : 0,
    "LdapErrorClosedSession" : 0,
    "LdapNormalClosedSession" : 0,
    "LdapTimeoutClosedSession" : 0,
    "LdapTotalDeletedSession" : 0,
    "LdapTotalOpenedSession" : 0,
    "MachineIp" : "10.70.2.15",
    "MachineName" : "zdpa2brprbis01isb",
    "MaxCpuUsage" : 1,
    "MemoryUsage" : 24,
    "NumberIpsecDecrypted" : 0,
    "NumberIpsecReceived" : 0,
    "OpenControlSessions" : 6,
    "OpenRTPSessions" : 0,
    "OpenUserDataSessions" : 0,
    "PacketPoolUtilization" : 0,
    "PfcpCorrelationRate" : 0.0,
    "PfcpCorrelationRateLast1K" : 0.0,
    "ProbeID" : "1193",
    "ProcessRestart" : 0,
    "ProcessingRingUtilization" : 0,
    "QAHistoricalFailedTracesInTheLastMin" : 0,
    "QAHistoricalTraceBitsPassedCapturePerSec" : 0,
    "QAHistoricalTraceBitsPassedFilterPerSec" : 0,
    "QAHistoricalTraceFilterRingUtilization" : 0,
    "QAHistoricalTracePacketPassedCapturePerSec" : 0,
    "QAHistoricalTracePacketPassedFilterPerSec" : 0,
    "QAHistoricalTracesInTheLastMin" : 0,
    "QAOnlineDroppedPacketOnlineRingFull" : 0,
    "QAOnlineFailedTracesInTheLastMin" : 0,
    "QAOnlineInputBitsPerSecond" : 0,
    "QAOnlineInputPacketsPerSecond" : 0,
    "QAOnlineTraceBitsPassedFilterPerSec" : 0,
    "QAOnlineTraceFilterRingUtilization" : 0,
    "QAOnlineTracePacketPassedFilterPerSec" : 0,
    "QAOnlineTracesInTheLastMin" : 0,
    "QATSharkTraceFilterRingUtilization" : 0,
    "QATotalPacketsDroppedPublisherFull" : 0,
    "QTraceHistoricalChunkFailureInLastMinute" : 0,
    "QTraceHistoricalChunkSuccessInLastMinute" : 0,
    "QTraceHistoricalMaxConcurrentReqInLastMinute" : 0,
    "QTraceHistoricalSifReqFailedInLastMinute" : 0,
    "QTraceOnlineMaxConcurrentReqInLastMinute" : 0,
    "QTraceOnlineSifReqFailedInLastMinute" : 0,
    "QTraceOnlineSifReqLatency" : 0.0,
    "RtpCurrentOpenSession" : 0,
    "RtpCurrentRecordedStream" : 0,
    "RtpTotalClosedSession" : 431120,
    "RtpTotalOpenedSession" : 431120,
    "RtpTotalRecordedStream" : 0,
    "RxPacketCountPerProtocol" : {
        "A11" : 0,
        "ARP" : 6,
        "BSSGP" : 0,
        "CHAP" : 0,
        "DIAMETER" : 0,
        "DNS" : 4,
        "ESP" : 0,
        "FP_MAC" : 0,
        "FTP" : 0,
        "GI/SGI" : 0,
        "GTP-C" : 0,
        "GTP-U" : 0,
        "GTP_PRIME" : 0,
        "H323" : 0,
        "HTTP" : 0,
        "HTTP/XCAP" : 0,
        "HTTPS" : 0,
        "HTTP_XML" : 0,
        "ICMP" : 0,
        "IGMP" : 0,
        "IPCP" : 0,
        "ISDN" : 0,
        "IU" : 0,
        "LCP" : 0,
        "LCSAP" : 0,
        "LDAP" : 0,
        "LSSU" : 0,
        "MEGACO" : 46,
        "MGCP" : 0,
        "MOBILE_IP" : 0,
        "MSRP" : 0,
        "MTP2" : 0,
        "MTP3" : 0,
        "MTP3 ALCAP" : 0,
        "MTP3 SCC" : 0,
        "NDP" : 0,
        "NON-TCP/UDP" : 0,
        "PAP" : 0,
        "PFCP" : 0,
        "POP3" : 0,
        "RADIUS" : 0,
        "RTCP" : 0,
        "RTP" : 0,
        "RTSP" : 0,
        "S1AP" : 0,
        "SBCAP" : 0,
        "SCTP" : 0,
        "SCTP_WITHOUT_L5-L7" : 0,
        "SGSAP" : 0,
        "SIP" : 24,
        "SIPoTLS" : 0,
        "SMPP" : 0,
        "SMTP" : 0,
        "SNMP" : 0,
        "SS7" : 0,
        "SS7_ANSI_TCAP" : 0,
        "SS7_TCAP" : 0,
        "T38" : 0,
        "UNDEFINED" : 0,
        "WAP SESSION_SERVICE" : 0,
        "X2AP" : 0
    },
    "RxPacketCountPerSource" : [ 
        {
            "IP" : "10.90.0.11",
            "RxPackets" : 3735166
        }, 
        {
            "IP" : "10.90.0.12",
            "RxPackets" : 2709086
        }, 
        {
            "IP" : "10.90.0.19",
            "RxPackets" : 973233214
        }, 
        {
            "IP" : "10.90.0.20",
            "RxPackets" : 975474184
        }, 
        {
            "IP" : "10.90.0.21",
            "RxPackets" : 989159322
        }, 
        {
            "IP" : "10.90.0.22",
            "RxPackets" : 973749771
        }
    ],
    "RxXDRsPerSecond" : 0.0,
    "S1APCdrsWithImsiRate" : 0,
    "S1APCdrsWithImsiRateLast10K" : 0,
    "S1APDecipherRate" : 0.0,
    "S1APDecipherRateWithImsi" : 0.0,
    "S1APDecipherRateWithImsiLast1K" : 0.0,
    "S1APPacketsWithImsiRate" : 0,
    "S1APPacketsWithImsiRateLast10K" : 0,
    "S1APPagingImsiResolvingRate" : 0.0,
    "SignalingCurrentDaysRetention" : 7.03,
    "SignalingFailedToSaveBps" : 0,
    "SignalingSavedBps" : 832,
    "SignalingStorageUsage" : 1,
    "SipByeWithoutDialog" : 16,
    "SipClosedCalls" : 431643,
    "SipClosedDialogs" : 431643,
    "SipClosedSessions" : 678761,
    "SipInviteTimeout" : 1,
    "SipOpenedCalls" : 431643,
    "SipOpenedDialogs" : 431643,
    "SipOpenedSessions" : 678767,
    "SipResponsesWithoutTransaction" : 51,
    "SiteName" : "DPA2b",
    "Ss7TcapClosedCamelInapCalls" : 0,
    "Ss7TcapLiveCamelInapCalls" : 0,
    "Ss7TcapLiveMapCalls" : 0,
    "Ss7TcapMapCloseCalls" : 0,
    "Ss7TcapMapOpenCalls" : 0,
    "Ss7TcapOpenedCamelInapCalls" : 0,
    "Ss7TcapTimeoutCamelInapCalls" : 0,
    "Ss7TcapTimeoutMapCalls" : 0,
    "StartTime" : 1566492240075,
    "SwRestart" : 0,
    "TotalFailedTxPps" : 0,
    "TotalRxBps" : 0,
    "TotalRxPps" : 0,
    "TotalTxBps" : 0,
    "TotalTxPps" : 0,
    "TxCDRsPerSecond" : 0,
    "TxRingUtilization" : 0,
    "TxXDRsPerSecond" : 0.0,
    "UpTime" : 1564684362636,
    "UserPlaneCurrentDaysRetention" : 0.0,
    "WhiteListCurrentDaysRetention" : 0.0,
    "WriterThreadBufferUtilization" : 0,
    "internalvNIC1Connectivity" : 1,
    "internalvNIC1TotalRxBps" : 0,
    "internalvNIC1TotalRxPps" : 0,
    "internalvNIC1TotalTxBps" : 0,
    "internalvNIC1TotalTxPps" : 0,
    "TimeStamp" : 1566492240633,
    "TimeStampDisplay" :    "2019-08-22T16:44:00.633Z",
    "StartTimeDisplay" : "2019-08-22T16:44:00.075Z",
    "UpTimeDisplay" : "2019-08-01T18:32:42.636Z"
}
const unique = 20
module.exports.getDocs = () => {
    const docs = [];
    const VMdocs = [];
    for(let i = 0; i < unique; i++){
        const Mdoc = new Object(document);
        const VMdoc = new Object(CDR_Health_VM);
        Mdoc.MachineIp = 'IP'+i;
        Mdoc.MachineName = Mdoc.MachineName + i;
        //Mdoc.MachineType = 'randomMiddle';
        Mdoc.StartTime = new Date();
        Mdoc.TimeStamp = new Date();
        Mdoc.StartTimeDisplay = Mdoc.StartTime.toUTCString();
        Mdoc.TimeStampDisplay = Mdoc.TimeStamp.toUTCString();
        docs.push(Mdoc);

        VMdoc.MachineIP = 'IP'+i;
        VMdoc.MachineName = Mdoc.MachineName + i;
        VMdoc.MachineType = 'randomvProbe';
        VMdoc.StartTime = new Date();
        VMdoc.TimeStamp = new Date();
        VMdoc.StartTimeDisplay = VMdoc.StartTime.toUTCString();
        VMdoc.TimeStampDisplay = VMdoc.TimeStamp.toUTCString();
        VMdocs.push(VMdoc);
    }
    return {
        "Mdocs": [...docs],
        "VMdocs": [...VMdocs]
    }
}